import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    borderBottomWidth: 1,
    gap: 10,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  title: {
    flex: 1,
    minWidth: 0,
    fontSize: 22,
    fontWeight: '700',
  },
  count: {
    fontSize: 13,
    fontWeight: '500',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 10,
  },
  headerAccessoryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 6,
    alignItems: 'center',
  },
  headerAccessoryLeft: {
    flex: 1,
    alignItems: 'flex-start',
  },
  headerAccessoryControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerAccessoryRight: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  sortButton: {
    borderWidth: 1,
    borderRadius: 18,
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBadge: {
    position: 'absolute',
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    right: -3,
    top: -4,
  },
  filterBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  bulkBar: {
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
  },
  bulkCount: {
    fontSize: 12,
    fontWeight: '600',
  },
  bulkStatusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  bulkStatusActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bulkExitButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bulkLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bulkLoadingText: {
    fontSize: 11,
    fontWeight: '500',
  },
  bulkMoveRow: {
    gap: 6,
    paddingVertical: 2,
  },
  bulkMoveButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  bulkMoveText: {
    fontSize: 12,
    fontWeight: '500',
  },
  bulkActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  bulkActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  bulkActionText: {
    fontSize: 12,
    fontWeight: '600',
  },
  bulkOrganizeCard: {
    width: '100%',
    maxWidth: 440,
    maxHeight: '86%',
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  bulkOrganizeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
  },
  bulkOrganizeTitleRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  bulkOrganizeTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  bulkOrganizeTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  bulkOrganizeSubtitle: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
  },
  bulkOrganizeCloseButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bulkOrganizeScroll: {
    flexGrow: 0,
  },
  bulkOrganizeContent: {
    paddingHorizontal: 16,
    paddingBottom: 14,
    gap: 14,
  },
  bulkOrganizeSection: {
    gap: 8,
  },
  bulkOrganizeLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  bulkOrganizeChipRow: {
    gap: 8,
    paddingRight: 6,
  },
  bulkOrganizeChip: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  bulkOrganizeChipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  bulkOrganizeDateGrid: {
    gap: 10,
  },
  bulkOrganizeDateField: {
    gap: 6,
  },
  bulkOrganizeInput: {
    minHeight: 42,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
  },
  bulkOrganizePickerRow: {
    minHeight: 42,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  bulkOrganizePickerValue: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    fontWeight: '600',
  },
  bulkOrganizeValidation: {
    fontSize: 12,
    fontWeight: '600',
  },
  bulkOrganizeFooter: {
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    padding: 12,
  },
  bulkOrganizeFooterButton: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  bulkOrganizeFooterText: {
    fontSize: 14,
    fontWeight: '700',
  },
  bulkOrganizeApplyButton: {
    minHeight: 40,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
  },
  bulkOrganizeApplyText: {
    fontSize: 14,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 12,
    padding: 16,
    gap: 12,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  modalInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  modalButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  modalButtonDisabled: {
    opacity: 0.5,
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  sortList: {
    gap: 6,
  },
  sortItem: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  sortItemText: {
    fontSize: 14,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 16,
    minHeight: 44,
  },
  copilotPill: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginTop: 8,
    marginHorizontal: 16,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  copilotText: {
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  copilotHint: {
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
  copilotLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  copilotIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copilotContent: {
    flex: 1,
    minWidth: 0,
  },
  addButton: {
    width: 44,
    height: 44,
    backgroundColor: '#007AFF',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addAndEditButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addButtonDisabled: {
    opacity: 0.5,
  },
  typeaheadContainer: {
    marginTop: 8,
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
  },
  typeaheadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  typeaheadText: {
    flexShrink: 1,
    fontSize: 13,
  },
  quickAddHelp: {
    fontSize: 12,
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 8,
  },
  filterSection: {
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  filterChips: {
    gap: 8,
    alignItems: 'center',
  },
  filterChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '600',
  },
  taskFilterSheetRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  taskFilterSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  taskFilterSheet: {
    maxHeight: '82%',
    borderTopWidth: 1,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 18,
  },
  taskFilterSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  taskFilterSheetTitle: {
    fontSize: 17,
    fontWeight: '700',
  },
  taskFilterSheetHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  taskFilterTextButton: {
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  taskFilterTextButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  taskFilterIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskFilterSheetScroll: {
    maxHeight: '100%',
  },
  taskFilterSheetContent: {
    gap: 12,
    paddingBottom: 20,
  },
  taskFilterSectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  taskFilterInput: {
    borderWidth: 1,
    borderRadius: 10,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 15,
  },
  taskFilterChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  taskFilterMatchModeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  taskFilterMatchModeLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  taskFilterMatchModeControl: {
    minHeight: 36,
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 18,
    padding: 2,
  },
  taskFilterMatchModeButton: {
    minWidth: 52,
    minHeight: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    paddingHorizontal: 10,
  },
  taskFilterMatchModeButtonText: {
    fontSize: 12,
    fontWeight: '700',
  },
  taskFilterChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  taskFilterChipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  list: {
    flex: 1,
  },
  staticList: {
    flex: 1,
  },
  staticItem: {
    marginBottom: 0,
  },
  projectReorderModeBar: {
    minHeight: 44,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  projectReorderTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: '700',
  },
  projectReorderModeButton: {
    minHeight: 36,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  projectReorderModeButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  projectReorderIconButton: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  projectDragGroup: {
    paddingHorizontal: 12,
  },
  projectDragList: {
    overflow: 'visible',
  },
  projectDragTaskRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
  },
  projectDragTaskRowActive: {
    opacity: 0.92,
  },
  projectReorderTaskCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 72,
    marginBottom: 8,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    justifyContent: 'center',
  },
  projectReorderTaskTitle: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 19,
  },
  projectReorderTaskMeta: {
    marginTop: 3,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 15,
  },
  projectDragHandle: {
    width: 44,
    marginBottom: 8,
    minHeight: 72,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listContent: {
    padding: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 6,
    paddingTop: 10,
    paddingBottom: 6,
  },
  sectionHeaderTitleBlock: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  sectionCount: {
    fontSize: 11,
    fontWeight: '600',
  },
  sectionReorderControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sectionReorderButton: {
    width: 32,
    height: 32,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionReorderButtonDisabled: {
    opacity: 0.4,
  },
  taskItem: {
    flexDirection: 'row',
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    alignItems: 'center',
  },
  taskContent: {
    flex: 1,
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 4,
  },
  taskDescription: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  taskMeta: {
    fontSize: 12,
    color: '#666',
  },
  deleteButton: {
    display: 'none',
  },
  deleteAction: {
    backgroundColor: '#EF4444',
    justifyContent: 'center',
    alignItems: 'center',
    width: 80,
    height: '100%',
  },
  promoteAction: {
    backgroundColor: '#3B82F6',
    justifyContent: 'center',
    alignItems: 'center',
    width: 80,
    height: '100%',
  },
  actionText: {
    color: '#fff',
    fontWeight: '600',
    padding: 20,
  },
  badgeContainer: {
    justifyContent: 'center',
    paddingLeft: 8,
  },
  searchInput: {
    marginHorizontal: 16,
    marginVertical: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    fontSize: 16,
    backgroundColor: '#f9f9f9',
  },
});
