import type { AppSettings, SettingsSyncPreferences, SyncBackend } from '@mindwtr/core';

export type SettingsSyncLabels = {
    dataTransfer: string;
    dataTransferDesc: string;
    exportBackup: string;
    exportBackupDesc: string;
    restoreBackup: string;
    restoreBackupDesc: string;
    importTodoist: string;
    importTodoistDesc: string;
    importTickTick: string;
    importTickTickDesc: string;
    importDgt: string;
    importDgtDesc: string;
    importOmniFocus: string;
    importOmniFocusDesc: string;
    diagnostics: string;
    diagnosticsDesc: string;
    analyticsHeartbeat: string;
    analyticsHeartbeatDesc: string;
    analyticsHeartbeatDisableTitle: string;
    analyticsHeartbeatDisableDesc: string;
    analyticsHeartbeatDisableConfirm: string;
    analyticsHeartbeatKeepEnabled: string;
    debugLogging: string;
    debugLoggingDesc: string;
    logFile: string;
    clearLog: string;
    sync: string;
    syncDescription: string;
    syncBackend: string;
    syncBackendOff: string;
    syncBackendFile: string;
    syncBackendWebdav: string;
    syncBackendCloud: string;
    syncBackendCloudkit: string;
    syncBackendChoiceHint: string;
    syncBackendGroupCloud: string;
    syncBackendGroupCloudDesc: string;
    syncBackendGroupFile: string;
    syncBackendGroupFileDesc: string;
    syncBackendGroupAdvanced: string;
    syncBackendGroupAdvancedDesc: string;
    syncPreferences: string;
    syncPreferencesDesc: string;
    syncPreferenceAppearance: string;
    syncPreferenceLanguage: string;
    syncPreferenceGtd: string;
    syncPreferenceSavedFilters: string;
    syncPreferenceExternalCalendars: string;
    syncPreferenceAi: string;
    syncPreferenceAiHint: string;
    backgroundSync: string;
    backgroundSyncDesc: string;
    syncFolderLocation: string;
    savePath: string;
    browse: string;
    pathHint: string;
    webdavUrl: string;
    webdavHint: string;
    webdavUsername: string;
    webdavPassword: string;
    webdavSave: string;
    testConnection: string;
    webdavTestHint: string;
    webdavTestAccessibility: string;
    allowInsecureHttp: string;
    allowInsecureHttpHint: string;
    cloudUrl: string;
    cloudHint: string;
    cloudToken: string;
    cloudRememberToken: string;
    cloudRememberTokenHint: string;
    cloudSave: string;
    cloudProvider: string;
    cloudProviderSelfHosted: string;
    cloudProviderDropbox: string;
    cloudProviderCloudkit: string;
    cloudkitDesc: string;
    dropboxAppKey: string;
    dropboxAppKeyHint: string;
    dropboxRedirectUri: string;
    dropboxStatus: string;
    dropboxConnected: string;
    dropboxNotConnected: string;
    dropboxConnect: string;
    dropboxDisconnect: string;
    dropboxTest: string;
    dropboxTestReachable: string;
    dropboxTestFailed: string;
    syncNow: string;
    syncing: string;
    syncQueued: string;
    lastSync: string;
    lastSyncSuccess: string;
    lastSyncConflict: string;
    lastSyncError: string;
    lastSyncConflicts: string;
    lastSyncSkew: string;
    lastSyncAdjusted: string;
    lastSyncConflictIds: string;
    syncConflictKeptThisDevice: string;
    syncConflictKeptOtherDevice: string;
    syncConflictChanged: string;
    syncConflictDeleteRestore: string;
    syncConflictMore: string;
    syncHistory: string;
    recoverySnapshots: string;
    recoverySnapshotsDesc: string;
    recoverySnapshotsLoading: string;
    recoverySnapshotsEmpty: string;
    recoverySnapshotsRestore: string;
    recoverySnapshotsConfirm: string;
    recoverySnapshotsConfirmTitle: string;
    recoverySnapshotsConfirmCancel: string;
    attachmentsCleanup: string;
    attachmentsCleanupDesc: string;
    attachmentsCleanupLastRun: string;
    attachmentsCleanupNever: string;
    attachmentsCleanupPendingDeletes: string;
    attachmentsCleanupPendingDeletesClear: string;
    attachmentsCleanupPendingDeletesConfirm: string;
    attachmentsCleanupPendingDeletesConfirmTitle: string;
    attachmentsCleanupRun: string;
    attachmentsCleanupRunning: string;
};

export type CloudProvider = 'selfhosted' | 'dropbox';
export type DropboxTestState = 'idle' | 'success' | 'error';
export type SyncPreferences = SettingsSyncPreferences;

export type SettingsSyncPageProps = {
    t: SettingsSyncLabels;
    isTauri: boolean;
    loggingEnabled: boolean;
    analyticsHeartbeatAvailable: boolean;
    analyticsHeartbeatEnabled: boolean;
    logPath: string;
    onToggleLogging: () => void;
    onAnalyticsHeartbeatChange: (enabled: boolean) => Promise<void> | void;
    onClearLog: () => void;
    syncBackend: SyncBackend;
    onSetSyncBackend: (backend: SyncBackend) => void;
    syncPreferences: AppSettings['syncPreferences'] | undefined;
    onUpdateSyncPreferences: (updates: Partial<SyncPreferences>) => Promise<void> | void;
    syncPath: string;
    onSyncPathChange: (value: string) => void;
    onSaveSyncPath: () => Promise<void> | void;
    onBrowseSyncPath: () => void;
    webdavUrl: string;
    webdavUsername: string;
    webdavPassword: string;
    webdavHasPassword: boolean;
    webdavAllowInsecureHttp: boolean;
    isSavingWebDav: boolean;
    isTestingWebDav: boolean;
    webdavTestState: 'idle' | 'success' | 'error';
    onWebdavUrlChange: (value: string) => void;
    onWebdavUsernameChange: (value: string) => void;
    onWebdavPasswordChange: (value: string) => void;
    onWebdavAllowInsecureHttpChange: (value: boolean) => void;
    onSaveWebDav: () => Promise<void> | void;
    onTestWebDavConnection: () => Promise<void> | void;
    cloudUrl: string;
    cloudToken: string;
    cloudRememberToken: boolean;
    cloudAllowInsecureHttp: boolean;
    cloudProvider: CloudProvider;
    dropboxAppKey: string;
    dropboxConfigured: boolean;
    dropboxConnected: boolean;
    dropboxBusy: boolean;
    dropboxAuthInProgress: boolean;
    dropboxRedirectUri: string;
    dropboxTestState: DropboxTestState;
    onCloudUrlChange: (value: string) => void;
    onCloudTokenChange: (value: string) => void;
    onCloudRememberTokenChange: (value: boolean) => void;
    onCloudAllowInsecureHttpChange: (value: boolean) => void;
    onCloudProviderChange: (provider: CloudProvider) => void;
    onSaveCloud: () => Promise<void> | void;
    onConnectDropbox: () => Promise<void> | void;
    onDisconnectDropbox: () => Promise<void> | void;
    onTestDropboxConnection: () => Promise<void> | void;
    onSyncNow: () => Promise<void> | void;
    isSyncing: boolean;
    syncQueued: boolean;
    syncLastResult: 'success' | 'error' | null;
    syncLastResultAt: string | null;
    syncError: string | null;
    lastSyncDisplay: string;
    lastSyncStatus: AppSettings['lastSyncStatus'];
    lastSyncStats: AppSettings['lastSyncStats'] | null;
    lastSyncHistory: AppSettings['lastSyncHistory'] | null;
    conflictCount: number;
    lastSyncError?: string;
    attachmentsLastCleanupDisplay: string;
    pendingRemoteDeleteCount: number;
    onClearPendingRemoteDeletes: () => Promise<void> | void;
    onRunAttachmentsCleanup: () => Promise<void> | void;
    isCleaningAttachments: boolean;
    snapshots: string[];
    isLoadingSnapshots: boolean;
    isRestoringSnapshot: boolean;
    transferAction: null | 'export' | 'restore' | 'import';
    onRestoreSnapshot: (snapshotFileName: string) => Promise<boolean | void> | boolean | void;
    onExportBackup: () => Promise<void> | void;
    onRestoreBackup: () => Promise<void> | void;
    onImportTodoist: () => Promise<void> | void;
    onImportTickTick: () => Promise<void> | void;
    onImportDgt: () => Promise<void> | void;
    onImportOmniFocus: () => Promise<void> | void;
};
