export const PROJECTS_SIDEBAR_WIDTH_STORAGE_KEY = 'mindwtr:projects:sidebarWidth';
export const PROJECTS_SIDEBAR_COLLAPSED_WIDTH = 56;
export const PROJECTS_SIDEBAR_DEFAULT_WIDTH = 304;
export const PROJECTS_SIDEBAR_MIN_WIDTH = 240;
export const PROJECTS_SIDEBAR_COMPACT_MAX_WIDTH = 520;
export const PROJECTS_SIDEBAR_MAX_WIDTH = 1200;
export const PROJECTS_WORKSPACE_MIN_WIDTH = 380;
export const PROJECTS_SIDEBAR_WIDE_BREAKPOINT = 1536;
export const PROJECTS_SIDEBAR_WIDE_WIDTH_RATIO = 0.34;
export const PROJECTS_SIDEBAR_KEYBOARD_STEP = 24;

export const PROJECTS_VIEW_DEFAULT_MAX_WIDTH = 1344;
export const PROJECTS_VIEW_WIDE_MAX_WIDTH = 1408;
export const PROJECTS_VIEW_WIDE_BREAKPOINT = 1536;
