import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1 },
    scrollView: { flex: 1 },
    scrollContent: { padding: 16 },
    topBar: {
        height: 52,
        borderBottomWidth: StyleSheet.hairlineWidth,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 8,
    },
    topBarBackButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    topBarBackButtonHidden: {
        opacity: 0,
    },
    topBarTitle: {
        fontSize: 17,
        fontWeight: '700',
    },
    subHeader: { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 12 },
    backButton: { fontSize: 16, fontWeight: '500' },
    subHeaderTitle: { fontSize: 18, fontWeight: '600' },
    description: { fontSize: 13, marginBottom: 12, paddingHorizontal: 4, lineHeight: 18 },
    sectionTitle: { fontSize: 13, fontWeight: '600', textTransform: 'uppercase', marginBottom: 8, marginLeft: 4 },
    menuGroupStack: { paddingTop: 16, gap: 14 },
    menuCard: { borderRadius: 12, overflow: 'hidden' },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderBottomWidth: 1,
        gap: 12,
    },
    menuItemDetailed: { minHeight: 72, paddingVertical: 12 },
    menuLeft: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 13 },
    menuIconSlot: { width: 22, alignItems: 'center', justifyContent: 'center' },
    menuTextBlock: { flex: 1, minWidth: 0 },
    menuLabel: { fontSize: 17, fontWeight: '500' },
    menuDescription: { fontSize: 13, marginTop: 3, lineHeight: 18 },
    chevron: { fontSize: 24, fontWeight: '300' },
    menuRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    updateDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#ef4444' },
    settingCard: { borderRadius: 12, overflow: 'hidden' },
    aboutAppHeader: {
        minHeight: 196,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
        paddingVertical: 28,
        borderBottomWidth: 1,
    },
    aboutAppIcon: {
        width: 84,
        height: 84,
        borderRadius: 20,
        marginBottom: 16,
    },
    aboutAppName: {
        fontSize: 24,
        fontWeight: '700',
        marginBottom: 6,
    },
    aboutAppVersion: {
        fontSize: 15,
        fontWeight: '500',
    },
    settingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16 },
    settingRowColumn: { padding: 16 },
    sectionHeaderText: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.6, paddingHorizontal: 16, marginTop: 12, marginBottom: 4 },
    taskEditorPresetRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 16, paddingBottom: 16 },
    taskEditorPresetButton: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1 },
    taskEditorPresetButtonText: { fontSize: 13, fontWeight: '700' },
    taskEditorSectionHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16 },
    taskEditorSectionHeaderMain: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1, marginRight: 12 },
    taskEditorSectionCountBadge: {
        minWidth: 26,
        height: 26,
        borderRadius: 13,
        paddingHorizontal: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    taskEditorSectionCountText: { fontSize: 12, fontWeight: '700' },
    taskEditorCompactRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14 },
    taskEditorCompactRowMain: { flex: 1, flexDirection: 'row', alignItems: 'center' },
    taskEditorCompactRowBorder: { borderTopWidth: 1 },
    taskEditorVisibilityBadge: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    taskEditorSectionChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
    taskEditorSectionChip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, borderWidth: 1 },
    taskEditorSectionChipText: { fontSize: 12, fontWeight: '600' },
    taskEditorSheetOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'flex-end',
    },
    taskEditorSheetCard: {
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        borderWidth: 1,
        overflow: 'hidden',
    },
    taskEditorSheetHandle: {
        width: 42,
        height: 5,
        borderRadius: 999,
        alignSelf: 'center',
        marginTop: 10,
        marginBottom: 2,
    },
    taskEditorSheetActions: { flexDirection: 'row', gap: 10, marginTop: 12 },
    taskEditorSheetActionButton: {
        flex: 1,
        minHeight: 44,
        borderRadius: 12,
        borderWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingHorizontal: 12,
    },
    taskEditorSheetActionDisabled: { opacity: 0.45 },
    taskEditorSheetActionText: { fontSize: 14, fontWeight: '600' },
    taskEditorSheetDoneButton: {
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 12,
        minHeight: 48,
        alignItems: 'center',
        justifyContent: 'center',
    },
    taskEditorSheetDoneButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
    settingInfo: { flex: 1, marginRight: 16 },
    settingLabel: { fontSize: 16, fontWeight: '500' },
    settingDescription: { fontSize: 13, marginTop: 2 },
    settingValue: { fontSize: 16 },
    linkText: { fontSize: 16, color: '#3B82F6' },
    guideLinkInline: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 6,
        marginBottom: 12,
        minHeight: 32,
        paddingHorizontal: 4,
        paddingVertical: 4,
    },
    guideLinkLabel: { fontSize: 13, fontWeight: '700' },
    helpBox: { borderRadius: 12, padding: 16, marginBottom: 8, borderWidth: 1 },
    helpTitle: { fontSize: 15, fontWeight: '600', marginBottom: 8 },
    helpText: { fontSize: 13, lineHeight: 20 },
    backendToggle: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
    backendOption: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, borderWidth: 1 },
    backendOptionText: { fontSize: 13, fontWeight: '700' },
    dropdownButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        gap: 8,
    },
    dropdownValue: {
        flex: 1,
        fontSize: 13,
        fontWeight: '600',
    },
    dropdownChevron: {
        fontSize: 14,
        fontWeight: '600',
    },
    modelInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    modelTextInput: {
        flex: 1,
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
    },
    modelSuggestButton: {
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 10,
    },
    modelSuggestButtonText: {
        fontSize: 12,
        fontWeight: '600',
    },
    pickerOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'center',
        padding: 20,
    },
    pickerCard: {
        borderRadius: 16,
        borderWidth: 1,
        padding: 16,
        maxHeight: '70%',
    },
    pickerTitle: {
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 12,
    },
    pickerList: {
        flexGrow: 0,
    },
    pickerListContent: {
        gap: 8,
    },
    pickerOption: {
        borderWidth: 1,
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    pickerOptionText: {
        fontSize: 13,
        fontWeight: '600',
    },
    timePickerActions: {
        marginTop: 12,
        borderTopWidth: 1,
        paddingTop: 12,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 8,
    },
    timePickerActionButton: {
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    timePickerActionText: {
        fontSize: 15,
        fontWeight: '600',
    },
    gtdNavigationRow: {
        minHeight: 56,
        borderTopWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
    },
    gtdNavigationLabel: {
        flex: 1,
    },
    gtdTimeInput: {
        width: 104,
        height: 44,
        marginTop: 0,
        textAlign: 'center',
    },
    gtdSegmentedControl: {
        borderWidth: 1,
        borderRadius: 14,
        flexDirection: 'row',
        gap: 4,
        padding: 4,
    },
    gtdSegmentedOption: {
        flex: 1,
        minHeight: 38,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingHorizontal: 10,
    },
    gtdSegmentedOptionText: {
        fontSize: 14,
        fontWeight: '700',
    },
    inputGroup: { padding: 16 },
    textInput: { marginTop: 8, borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14 },
    inlineInputRow: { flexDirection: 'row', gap: 12 },
    inlineInputGroup: { flex: 1 },
    inlineInputLabel: { fontSize: 12, fontWeight: '600' },
    inlineTextInput: { marginTop: 6 },
    manageColorPicker: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginTop: 16,
    },
    manageColorOption: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(15, 23, 42, 0.15)',
    },
    manageColorOptionSelected: {
        borderWidth: 2,
        borderColor: '#0f172a',
    },
    manageEditorActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 10,
        marginTop: 20,
    },
    manageEditorButton: {
        minWidth: 92,
        minHeight: 42,
        borderRadius: 10,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 14,
    },
    manageEditorButtonPrimary: {
        backgroundColor: '#2563eb',
        borderColor: '#2563eb',
    },
    manageEditorButtonDisabled: {
        opacity: 0.5,
    },
    manageEditorButtonText: {
        fontSize: 14,
        fontWeight: '600',
    },
    manageEditorButtonPrimaryText: {
        color: '#FFFFFF',
    },
});
