export const labelFallback = {
    en: {
        title: 'Settings',
        general: 'General',
        integrations: 'Integrations',
        advanced: 'Advanced',
        subtitle: 'Customize your Mindwtr experience',
        searchPlaceholder: 'Search settings…',
        back: 'Back',
        features: 'Features',
        featuresDesc: 'Optional signals you can turn on when needed.',
        lookAndFeel: 'Look & Feel',
        localization: 'Localization',
        input: 'Input',
        windowBehavior: 'Window Behavior',
        appearance: 'Appearance',
        density: 'Density',
        densityDesc: 'Adjust list spacing to show more items on screen.',
        densityComfortable: 'Comfortable',
        densityCompact: 'Compact',
        textSize: 'Text size',
        textSizeDesc: 'Adjust interface text across the desktop app.',
        textSizeSmall: 'Small',
        textSizeDefault: 'Default',
        textSizeLarge: 'Large',
        textSizeExtraLarge: 'Extra large',
        showTaskAge: 'Show task age',
        showTaskAgeDesc: 'Display how long ago a task was created in task metadata.',
        gtd: 'GTD',
        gtdDesc: 'Tune the GTD workflow defaults.',
        inboxProcessing: 'Inbox processing',
        inboxProcessingDesc: 'Customize the inbox workflow to match your style.',
        inboxDefaultMode: 'Default mode',
        inboxModeGuided: 'Guided',
        inboxModeQuick: 'Quick',
        inboxTwoMinuteEnabled: 'Show the 2-minute shortcut',
        inboxTwoMinuteFirst: 'Ask the 2-minute rule first',
        inboxProjectFirst: 'Ask for project early',
        inboxContextStepEnabled: 'Include Contexts & Tags step',
        inboxScheduleEnabled: 'Allow scheduling during processing',
        inboxReferenceEnabled: 'Offer Reference during processing',
        captureDefault: 'Default capture method',
        captureDefaultDesc: 'Choose whether quick capture starts with text or audio.',
        captureDefaultText: 'Text',
        captureDefaultAudio: 'Audio',
        captureSaveAudio: 'Save audio attachments',
        captureSaveAudioDesc: 'Keep the audio file attached after transcription.',
        autoArchive: 'Auto-archive done tasks',
        autoArchiveDesc: 'Move completed tasks to Archived after a set number of days.',
        autoArchiveNever: 'Never (keep in Done)',
        autoArchiveDayUnit: 'days',
        defaultScheduleTime: 'Default schedule time',
        defaultScheduleTimeDesc: 'Optional. Pre-fills manual Start, Due, and Review time fields after you choose a date. Leave blank for date-only.',
        focusTaskLimit: "Today's focus limit",
        focusTaskLimitDesc: "Maximum tasks you can star for today's focus.",
        language: 'Language',
        weekStart: 'Week starts on',
        weekStartSunday: 'Sunday',
        weekStartMonday: 'Monday',
        weekStartSaturday: 'Saturday',
        dateFormat: 'Date format',
        dateFormatSystem: 'System default',
        dateFormatDmy: 'Day / Month / Year',
        dateFormatMdy: 'Month / Day / Year',
        dateFormatYmd: 'Year / Month / Day',
        timeFormat: 'Time format',
        timeFormatSystem: 'System default',
        timeFormat12h: '12-hour',
        timeFormat24h: '24-hour',
        keybindings: 'Keyboard Shortcuts',
        keybindingsDesc: 'Choose your preferred desktop keybinding style.',
        undoNotifications: 'Undo notifications',
        undoNotificationsDesc: 'Show an Undo toast after marking tasks Done or deleting tasks.',
        globalQuickAddShortcut: 'Global quick add shortcut',
        globalQuickAddShortcutDesc: 'Used system-wide for quick capture, even when Mindwtr is not focused.',
        globalQuickAddFlatpakDesc: 'Flatpak/Wayland does not allow Mindwtr to own this shortcut directly.',
        globalQuickAddFlatpakCommand: 'Flatpak custom shortcut command',
        globalQuickAddFlatpakCommandDesc: 'Bind this command in your desktop shortcut settings.',
        keybindingVim: 'Vim',
        keybindingEmacs: 'Emacs',
        viewShortcuts: 'View shortcuts',
        windowDecorations: 'Window decorations',
        windowDecorationsDesc: 'Show system title bar and window borders.',
        closeBehavior: 'Close window behavior',
        closeBehaviorDesc: 'Choose what happens when you close the window.',
        closeBehaviorAsk: 'Ask every time',
        closeBehaviorTray: 'Keep running in tray',
        closeBehaviorQuit: 'Quit the app',
        launchAtStartup: 'Launch at startup',
        launchAtStartupDesc: 'Start Mindwtr automatically when you sign in to this computer.',
        showTray: 'Show system tray icon',
        showTrayDesc: 'Display the app icon in your system tray for quick access.',
        automation: 'Automation',
        localApiServer: 'Enable local API server',
        localApiPort: 'Port',
        localApiPortDesc: 'Localhost only. Default: 3456.',
        localApiToken: 'Bearer token',
        localApiTokenDesc: 'Required in the Authorization header for every request.',
        localApiSecurityNote: 'Local apps and scripts with this token can read and change Mindwtr data.',
        localApiStopped: 'Off',
        localApiUnavailable: 'Desktop app only',
        localApiPortInvalid: 'Enter a port between 1024 and 65535.',
        taskEditorLayout: 'Task editor layout',
        taskEditorLayoutDesc: 'Choose which fields are shown by default in the task editor.',
        taskEditorLayoutHint: 'Hidden fields appear when they have content or after clicking “More options”.',
        taskEditorPresentation: 'Editor opening',
        taskEditorPresentationDesc: 'Choose how task editing opens when you use the desktop editor.',
        taskEditorPresentationInline: 'Side peek',
        taskEditorPresentationInlineDesc: 'Open the editor inline inside the current view for faster quick edits.',
        taskEditorPresentationModal: 'Pop-up',
        taskEditorPresentationModalDesc: 'Open the editor in a centered modal for focused editing.',
        taskEditorLayoutReset: 'Reset layout',
        taskEditorSection: 'Section',
        taskEditorDefaultOpen: 'Default-open sections',
        taskEditorOpenByDefault: 'Open by default',
        taskEditorDefaultOpenDesc: 'Keep these task editor sections expanded whenever they do not already have content.',
        taskEditorFieldStatus: 'Status',
        taskEditorFieldProject: 'Project',
        taskEditorFieldSection: 'Project section',
        taskEditorFieldArea: 'Area',
        taskEditorFieldPriority: 'Priority',
        taskEditorFieldEnergyLevel: 'Energy level',
        taskEditorFieldAssignedTo: 'Assigned to',
        taskEditorFieldContexts: 'Contexts',
        taskEditorFieldDescription: 'Description',
        taskEditorFieldTags: 'Tags',
        taskEditorFieldTimeEstimate: 'Time estimate',
        taskEditorFieldRecurrence: 'Recurrence',
        taskEditorFieldStartTime: 'Start date',
        taskEditorFieldDueDate: 'Due date',
        taskEditorFieldReviewAt: 'Review date',
        taskEditorFieldAttachments: 'Attachments',
        taskEditorFieldChecklist: 'Checklist',
        taskEditorFieldTextDirection: 'Text direction',
        featurePriorities: 'Priorities',
        featurePrioritiesDesc: 'Show a priority flag on tasks.',
        featureTimeEstimates: 'Time estimates',
        featureTimeEstimatesDesc: 'Add quick duration estimates for time blocking.',
        featurePomodoro: 'Pomodoro timer',
        featurePomodoroDesc: 'Enable the optional Pomodoro panel in Focus view.',
        pomodoroCustomPreset: 'Custom preset',
        pomodoroCustomPresetDesc: 'Add one extra focus/break preset. Matching a built-in preset keeps the built-in chips only.',
        pomodoroFocusMinutes: 'Focus minutes',
        pomodoroBreakMinutes: 'Break minutes',
        pomodoroLinkTask: 'Link timer to task',
        pomodoroLinkTaskDesc: 'Show the Timer task picker and Task done action in Focus.',
        pomodoroAutoStartBreaks: 'Auto-start breaks',
        pomodoroAutoStartBreaksDesc: 'Start the break timer automatically when a focus session ends.',
        pomodoroAutoStartFocus: 'Auto-start focus',
        pomodoroAutoStartFocusDesc: 'Start the next focus session automatically when a break ends.',
        notifications: 'Notifications',
        notificationsDesc: 'Enable task reminders and daily digest notifications.',
        notificationsEnable: 'Enable notifications',
        startDateNotifications: 'Start date reminders',
        startDateNotificationsDesc: 'Notify me when a task start date/time arrives.',
        dueDateNotifications: 'Due date reminders',
        dueDateNotificationsDesc: 'Notify me when a task due date/time arrives.',
        reviewAtNotifications: 'Review date reminders',
        reviewAtNotificationsDesc: 'Notify me when a review (tickler) date is due.',
        ai: 'AI Assistant',
        aiDesc: 'Optional help to clarify and break down tasks.',
        aiEnable: 'Enable AI assistant',
        aiProvider: 'Provider',
        aiProviderOpenAI: 'OpenAI',
        aiProviderGemini: 'Gemini',
        aiProviderAnthropic: 'Anthropic (Claude)',
        aiModel: 'Model',
        aiBaseUrl: 'Custom OpenAI-compatible base URL',
        aiBaseUrlHint: 'Leave blank for official OpenAI. Set this for local or third-party OpenAI-compatible APIs such as llama.cpp, Ollama, LM Studio, GLM, or vLLM.',
        aiBaseUrlModelHint: 'This model looks non-OpenAI. If you are using GLM or another OpenAI-compatible provider, set a custom base URL.',
        aiApiKey: 'API key',
        aiApiKeyHint: 'Stored locally on this device. Never synced. Official OpenAI requires a key. Custom OpenAI-compatible endpoints may also require one; leave it blank only if your endpoint allows unauthenticated requests.',
        aiReasoning: 'Reasoning effort',
        aiReasoningHint: 'Used by GPT-5 models.',
        aiEffortLow: 'Low',
        aiEffortMedium: 'Medium',
        aiEffortHigh: 'High',
        aiCopilotModel: 'Copilot model',
        aiCopilotHint: 'Used for fast autocomplete suggestions.',
        aiConsentTitle: 'Enable AI Features?',
        aiConsentDescription: 'To use this feature, your task data will be sent to {provider} for processing. This data is subject to their privacy policy. Mindwtr does not collect this data. Do you wish to proceed?',
        aiConsentCancel: 'Cancel',
        aiConsentAgree: 'Agree',
        aiThinkingBudget: 'Thinking budget',
        aiThinkingHint: 'Claude/Gemini only. 0 disables extended thinking.',
        aiThinkingEnable: 'Enable thinking',
        aiThinkingEnableDesc: 'Use extended reasoning for complex tasks.',
        aiThinkingOff: 'Off',
        aiThinkingLow: 'Low',
        aiThinkingMedium: 'Medium',
        aiThinkingHigh: 'High',
        speechTitle: 'Speech to text',
        speechDesc: 'Transcribe voice captures and map them into task fields.',
        speechEnable: 'Enable speech to text',
        speechProvider: 'Speech provider',
        speechProviderOffline: 'On-device (Whisper)',
        speechModel: 'Speech model',
        speechOfflineModel: 'Offline model',
        speechOfflineModelDesc: 'Download once to transcribe fully offline.',
        speechOfflineReady: 'Model downloaded',
        speechOfflineNotDownloaded: 'Model not downloaded',
        speechOfflineDownload: 'Download',
        speechOfflineDownloadSuccess: 'Download complete',
        speechOfflineDelete: 'Delete',
        speechOfflineDownloadError: 'Offline model download failed',
        speechLanguage: 'Audio language',
        speechLanguageHint: 'Use a language name or code, or leave blank to auto-detect.',
        speechLanguageAuto: 'Auto (detect language)',
        speechMode: 'Processing mode',
        speechModeHint: 'Smart parse extracts dates and fields; transcript-only just transcribes.',
        speechModeSmart: 'Smart parse',
        speechModeTranscript: 'Transcript only',
        speechFieldStrategy: 'Field mapping',
        speechFieldStrategyHint: 'Choose where the transcript should land by default.',
        speechFieldSmart: 'Smart',
        speechFieldTitle: 'Title',
        speechFieldDescription: 'Description',
        dailyDigest: 'Daily Digest',
        dailyDigestDesc: 'Morning briefing and evening review prompts.',
        dailyDigestMorning: 'Morning briefing',
        dailyDigestEvening: 'Evening review',
        weeklyReview: 'Weekly review',
        weeklyReviewDesc: 'Get a weekly review reminder at your chosen time.',
        weeklyReviewDay: 'Review day',
        weeklyReviewTime: 'Review time',
        weeklyReviewConfig: 'Weekly review flow',
        weeklyReviewConfigDesc: 'Configure which steps appear in weekly review.',
        weeklyReviewIncludeContextsStep: 'Include Contexts step',
        weeklyReviewIncludeContextsStepDesc: 'Show a dedicated contexts review step between Waiting For and Projects.',
        on: 'On',
        off: 'Off',
        visible: 'Shown',
        hidden: 'Hidden',
        manage: 'Manage',
        dataTransfer: 'Data Transfer',
        dataTransferDesc: 'Export a full backup, restore local data from backup, or import Todoist, DGT GTD, and OmniFocus exports.',
        exportBackup: 'Export Backup',
        exportBackupDesc: 'Save the current local data as a JSON backup file.',
        restoreBackup: 'Restore Backup',
        restoreBackupDesc: 'Replace local data from a Mindwtr backup JSON file.',
        importTodoist: 'Import from Todoist',
        importTodoistDesc: 'Import Todoist CSV or ZIP exports into Mindwtr projects.',
        importDgt: 'Import from DGT GTD',
        importDgtDesc: 'Import DGT GTD JSON or ZIP exports into Mindwtr areas, projects, and tasks.',
        importOmniFocus: 'Import from OmniFocus',
        importOmniFocusDesc: 'Import OmniFocus CSV, JSON, or ZIP exports into Mindwtr projects and inbox tasks.',
        diagnostics: 'Diagnostics',
        diagnosticsDesc: 'Help troubleshoot issues.',
        analyticsHeartbeat: 'Anonymous usage heartbeat',
        analyticsHeartbeatDesc: 'Send a small daily diagnostic signal for app health and platform/version adoption. No task or personal data is included.',
        analyticsHeartbeatDisableTitle: 'Disable anonymous heartbeat?',
        analyticsHeartbeatDisableDesc: 'The heartbeat does not include tasks, projects, notes, files, AI prompts, email, name, contacts, or account data. It helps measure active platforms and versions. If you disable it, Mindwtr stops sending heartbeat requests from this install.',
        analyticsHeartbeatDisableConfirm: 'Disable',
        analyticsHeartbeatKeepEnabled: 'Keep enabled',
        debugLogging: 'Debug logging',
        debugLoggingDesc: 'Record errors locally to share with support.',
        logFile: 'Log file',
        clearLog: 'Clear log',
        sync: 'Sync',
        syncDescription:
            'Configure a secondary folder to sync your data with (e.g., Dropbox, Syncthing). For near real-time multi-device sync, WebDAV is recommended over folder sync tools.',
        syncBackend: 'Sync backend',
        syncBackendOff: 'Off',
        syncBackendFile: 'File',
        syncBackendWebdav: 'WebDAV',
        syncBackendCloud: 'Cloud',
        syncBackendCloudkit: 'iCloud',
        syncPreferences: 'Settings sync options',
        syncPreferencesDesc: 'Choose which preferences stay in sync across devices.',
        syncPreferenceAppearance: 'Appearance (theme, density, text size, task age)',
        syncPreferenceLanguage: 'Language & date format',
        syncPreferenceGtd: 'Scheduling defaults',
        syncPreferenceSavedFilters: 'Saved filters',
        syncPreferenceExternalCalendars: 'External calendar URLs',
        syncPreferenceAi: 'AI settings (models, providers)',
        syncPreferenceAiHint: 'API keys and local model paths are never synced.',
        backgroundSync: 'Background sync',
        backgroundSyncDesc: 'Desktop sync runs every 15 minutes while Mindwtr is running. Close-to-tray keeps it active; launch-at-startup can start it after sign-in. Quitting the app stops desktop background sync.',
        attachmentsCleanup: 'Attachment cleanup',
        attachmentsCleanupDesc: 'Remove deleted or orphaned attachment files from your device and sync storage.',
        attachmentsCleanupLastRun: 'Last cleanup',
        attachmentsCleanupNever: 'Never',
        attachmentsCleanupPendingDeletes: 'Pending remote deletes',
        attachmentsCleanupPendingDeletesClear: 'Clear pending deletes',
        attachmentsCleanupPendingDeletesConfirm: 'Only clear these if you no longer want Mindwtr to delete those files from the old sync backend. This does not delete any files.',
        attachmentsCleanupPendingDeletesConfirmTitle: 'Clear pending attachment deletes?',
        attachmentsCleanupRun: 'Run cleanup',
        attachmentsCleanupRunning: 'Cleaning...',
        calendar: 'Calendar',
        calendarDesc: 'View external calendars via ICS subscription URLs or local .ics files.',
        externalCalendars: 'External calendars',
        calendarName: 'Name',
        calendarUrl: 'ICS URL',
        calendarAdd: 'Add calendar',
        calendarChooseLocalFile: 'Choose local .ics file',
        calendarRemove: 'Remove',
        calendarSystemTitle: 'Apple Calendar (macOS)',
        calendarSystemDesc: 'Read events from Apple Calendar accounts synced by macOS (iCloud, Google, Exchange) via EventKit.',
        calendarSystemStatus: 'Apple Calendar access',
        calendarSystemPermissionGranted: 'Granted',
        calendarSystemPermissionUndetermined: 'Not requested',
        calendarSystemPermissionDenied: 'Denied',
        calendarSystemPermissionUnsupported: 'Unsupported',
        calendarSystemRequestAccess: 'Request access',
        calendarSystemDeniedHint: 'Calendar access is denied. Enable Mindwtr in macOS System Settings > Privacy & Security > Calendars.',
        syncFolderLocation: 'Sync folder',
        savePath: 'Save',
        browse: 'Browse…',
        syncNow: 'Sync now',
        syncing: 'Syncing…',
        syncQueued: 'Sync queued',
        pathHint: 'Choose a folder (e.g., ~/Sync/mindwtr). With Syncthing: use Send & Receive + Watch for Changes, then press Sync now before switching devices.',
        webdavUrl: 'WebDAV URL',
        webdavUsername: 'Username',
        webdavPassword: 'Password',
        webdavSave: 'Save WebDAV',
        testConnection: 'Test connection',
        webdavTestHint: 'Verify URL and credentials without syncing data',
        webdavTestAccessibility: 'Test WebDAV connection',
        webdavHint: 'Point to a folder — Mindwtr will store data.json inside (e.g., https://example.com/remote.php/dav/files/user/mindwtr).',
        allowInsecureHttp: 'Allow insecure connections (HTTP)',
        allowInsecureHttpHint: 'Only local or private-network HTTP is allowed. Data will be sent unencrypted.',
        cloudUrl: 'Self-hosted URL',
        cloudToken: 'Access token',
        cloudSave: 'Save Self-Hosted',
        cloudHint: 'Use the base URL (e.g., https://example.com or https://example.com/mindwtr). Mindwtr will append /v1/data.',
        cloudProvider: 'Cloud provider',
        cloudProviderSelfHosted: 'Self-hosted',
        cloudProviderDropbox: 'Dropbox',
        cloudProviderCloudkit: 'iCloud',
        cloudkitDesc: 'Syncs your tasks, projects, and areas across Apple devices using iCloud. No setup required.',
        dropboxAppKey: 'Dropbox account',
        dropboxAppKeyHint: 'Dropbox app key is injected at build/release time.',
        dropboxRedirectUri: 'Redirect URI',
        dropboxStatus: 'Status',
        dropboxConnected: 'Connected',
        dropboxNotConnected: 'Not connected',
        dropboxConnect: 'Connect Dropbox',
        dropboxDisconnect: 'Disconnect Dropbox',
        dropboxTest: 'Test connection',
        dropboxTestReachable: 'Reachable',
        dropboxTestFailed: 'Failed',
        obsidianVault: 'Obsidian Vault',
        obsidianVaultDesc: 'Connect a local Obsidian vault and import Markdown checklist items as read-only external tasks.',
        obsidianEnable: 'Enable Obsidian integration',
        obsidianVaultPath: 'Vault folder',
        obsidianVaultPathHint: 'Select the root folder of your vault. Mindwtr reads Markdown notes from the configured scan folders.',
        obsidianScanFolders: 'Scan folders',
        obsidianScanFoldersHint: 'One relative folder per line. Use / to scan the whole vault.',
        obsidianInboxFile: 'Mindwtr inbox note',
        obsidianInboxFileHint: 'Relative Markdown path for tasks created from Mindwtr. Parent folders are created when needed.',
        obsidianTaskNotes: 'TaskNotes',
        obsidianTaskNotesDesc: 'TaskNotes files are detected automatically. Use these options to control archived imports and the format Mindwtr uses when it creates new vault tasks.',
        obsidianTaskNotesIncludeArchived: 'Include archived TaskNotes',
        obsidianTaskNotesIncludeArchivedHint: 'Leave this off to keep archived TaskNotes files out of the imported task list.',
        obsidianNewTaskFormat: 'New task format',
        obsidianNewTaskFormatHint: 'Auto follows the detected vault format. Use an override only if you want Mindwtr-created tasks to use a different format.',
        obsidianNewTaskFormatAuto: 'Auto-detect',
        obsidianNewTaskFormatInline: 'Inline checkbox',
        obsidianNewTaskFormatTaskNotes: 'TaskNotes note',
        obsidianWatching: 'Watching for vault changes.',
        obsidianWatcherUnavailable: 'Live updates unavailable.',
        obsidianSave: 'Save Obsidian settings',
        obsidianRemove: 'Disconnect vault',
        obsidianRescan: 'Rescan vault',
        obsidianRescanning: 'Scanning vault...',
        obsidianLastScanned: 'Last Obsidian scan',
        obsidianNeverScanned: 'Never scanned',
        obsidianMissingMarker: 'This folder does not contain a .obsidian directory. You can still save it if your vault layout is unconventional.',
        obsidianChooseVaultFailed: 'Failed to choose Obsidian vault folder.',
        obsidianSaveFailed: 'Failed to save Obsidian config.',
        obsidianRemoveFailed: 'Failed to remove Obsidian config.',
        obsidianScanFailed: 'Failed to scan Obsidian vault.',
        obsidianScanSuccess: 'Obsidian vault scanned.',
        lastSync: 'Last sync',
        lastSyncNever: 'Never',
        lastSyncSuccess: 'Sync completed',
        lastSyncError: 'Sync failed',
        lastSyncConflict: 'Conflicts resolved',
        lastSyncConflicts: 'Conflicts',
        lastSyncSkew: 'Clock skew',
        lastSyncAdjusted: 'Timestamp fixes',
        lastSyncConflictIds: 'Conflict IDs',
        syncHistory: 'Sync history',
        recoverySnapshots: 'Recovery snapshots',
        recoverySnapshotsDesc: 'Created before sync. Kept for up to 7 days (max 5 files).',
        recoverySnapshotsLoading: 'Loading snapshots…',
        recoverySnapshotsEmpty: 'No snapshots yet.',
        recoverySnapshotsRestore: 'Restore',
        recoverySnapshotsConfirm: 'Restore snapshot {snapshot}? This will replace current local data.',
        recoverySnapshotsConfirmTitle: 'Restore snapshot?',
        recoverySnapshotsConfirmCancel: 'Cancel',
        about: 'About',
        version: 'Version',
        installChannel: 'Install Channel',
        developer: 'Developer',
        website: 'Developer Website',
        github: 'GitHub',
        documentation: 'Documentation',
        sponsorProject: 'Sponsor Project',
        license: 'License',
        checkForUpdates: 'Check for Updates',
        checkStoreUpdates: 'Check Microsoft Store',
        checking: 'Checking…',
        upToDate: 'You are using the latest version!',
        updateAvailable: 'Update Available',
        checkFailed: 'Failed to check for updates',
        storeUpdateHint: 'Updates are managed by Microsoft Store.',
        download: 'Download',
        downloadStarting: 'Opening download…',
        downloadStarted: 'Download started in your browser.',
        downloadFailed: 'Failed to open download link.',
        downloadChecksumMismatch: 'Checksum verification failed. Please download again from the release page.',
        downloadRecommended: 'Recommended package',
        downloadAURHint: 'Arch detected: update via AUR',
        changelog: 'Changelog',
        noChangelog: 'No changelog available',
        later: 'Later',
        linuxUpdateHint: 'On Linux, Mindwtr cannot auto-install updates. After downloading, install via your package manager (e.g., yay -S mindwtr or paru -S mindwtr) or the downloaded package.',
        saved: 'Settings saved',
        selectSyncFolderTitle: 'Select sync folder',
        selectObsidianVaultTitle: 'Select Obsidian vault',
        system: 'System',
        light: 'Light',
        dark: 'Dark',
        eink: 'E-Ink',
        nord: 'Nord',
        sepia: 'Sepia',
    },
    zh: {
        title: '设置',
        general: '通用',
        integrations: '集成',
        advanced: '高级',
        subtitle: '自定义您的 Mindwtr 体验',
        searchPlaceholder: '搜索设置…',
        back: '返回',
        features: '功能',
        featuresDesc: '按需开启可选信号。',
        lookAndFeel: '外观与风格',
        localization: '本地化',
        input: '输入',
        windowBehavior: '窗口行为',
        appearance: '外观',
        density: '密度',
        densityDesc: '调整列表间距以显示更多内容。',
        densityComfortable: '舒适',
        densityCompact: '紧凑',
        textSize: '文字大小',
        textSizeDesc: '调整桌面应用中的界面文字。',
        textSizeSmall: '小',
        textSizeDefault: '默认',
        textSizeLarge: '大',
        textSizeExtraLarge: '特大',
        showTaskAge: '显示任务年龄',
        showTaskAgeDesc: '在任务元数据中显示任务创建距今多久。',
        gtd: 'GTD',
        gtdDesc: '调整 GTD 工作流默认设置。',
        inboxProcessing: '收集箱处理',
        inboxProcessingDesc: '按你的习惯调整收集箱处理流程。',
        inboxDefaultMode: '默认模式',
        inboxModeGuided: '引导式',
        inboxModeQuick: '快速',
        inboxTwoMinuteEnabled: '显示“两分钟内完成”快捷选项',
        inboxTwoMinuteFirst: '先询问两分钟规则',
        inboxProjectFirst: '提前询问项目归属',
        inboxContextStepEnabled: '包含情境与标签步骤',
        inboxScheduleEnabled: '处理中允许安排日期',
        inboxReferenceEnabled: '处理中提供参考资料选项',
        captureDefault: '默认捕获方式',
        captureDefaultDesc: '选择快速捕获默认使用文本或语音。',
        captureDefaultText: '文本',
        captureDefaultAudio: '语音',
        captureSaveAudio: '保留语音附件',
        captureSaveAudioDesc: '转录后仍保留音频文件。',
        autoArchive: '自动归档完成任务',
        autoArchiveDesc: '在设定天数后将已完成任务移入归档。',
        autoArchiveNever: '从不（保留在已完成）',
        autoArchiveDayUnit: '天',
        defaultScheduleTime: '默认安排时间',
        defaultScheduleTimeDesc: '可选。选择日期后自动填入开始、截止和回顾时间。留空则保持仅日期。',
        focusTaskLimit: '今日焦点上限',
        focusTaskLimitDesc: '每天可加星加入今日焦点的最大任务数。',
        language: '语言',
        weekStart: '每周开始于',
        weekStartSunday: '周日',
        weekStartMonday: '周一',
        weekStartSaturday: '周六',
        dateFormat: '日期格式',
        dateFormatSystem: '系统默认',
        dateFormatDmy: '日 / 月 / 年',
        dateFormatMdy: '月 / 日 / 年',
        dateFormatYmd: '年 / 月 / 日',
        timeFormat: '时间格式',
        timeFormatSystem: '系统默认',
        timeFormat12h: '12 小时',
        timeFormat24h: '24 小时',
        keybindings: '快捷键',
        keybindingsDesc: '选择桌面端偏好的快捷键风格。',
        undoNotifications: '撤销通知',
        undoNotificationsDesc: '在将任务标记为已完成或删除后显示可撤销提示。',
        globalQuickAddShortcut: '全局快速添加快捷键',
        globalQuickAddShortcutDesc: '用于系统级快速收集，即使 Mindwtr 未聚焦也可触发。',
        globalQuickAddFlatpakDesc: 'Flatpak/Wayland 环境无法由 Mindwtr 直接注册这个快捷键。',
        globalQuickAddFlatpakCommand: 'Flatpak 自定义快捷键命令',
        globalQuickAddFlatpakCommandDesc: '请在桌面环境的快捷键设置中绑定这个命令。',
        keybindingVim: 'Vim',
        keybindingEmacs: 'Emacs',
        viewShortcuts: '查看快捷键',
        windowDecorations: '窗口装饰',
        windowDecorationsDesc: '显示系统标题栏和窗口边框。',
        closeBehavior: '关闭窗口行为',
        closeBehaviorDesc: '选择关闭窗口时的操作。',
        closeBehaviorAsk: '每次询问',
        closeBehaviorTray: '保留在托盘',
        closeBehaviorQuit: '退出应用',
        launchAtStartup: '开机自动启动',
        launchAtStartupDesc: '登录这台电脑时自动启动 Mindwtr。',
        showTray: '显示系统托盘图标',
        showTrayDesc: '在系统托盘中显示应用图标以便快速访问。',
        automation: '自动化',
        localApiServer: '启用本地 API 服务器',
        localApiPort: '端口',
        localApiPortDesc: '仅限 localhost。默认：3456。',
        localApiToken: 'Bearer 令牌',
        localApiTokenDesc: '每个请求都必须在 Authorization 请求头中提供。',
        localApiSecurityNote: '拥有此令牌的本地应用和脚本可以读取并修改 Mindwtr 数据。',
        localApiStopped: '关闭',
        localApiUnavailable: '仅桌面应用可用',
        localApiPortInvalid: '请输入 1024 到 65535 之间的端口。',
        taskEditorLayout: '任务编辑布局',
        taskEditorLayoutDesc: '选择默认显示的任务编辑字段。',
        taskEditorLayoutHint: '隐藏字段仅在有内容或点击“更多选项”后显示。',
        taskEditorPresentation: '编辑器打开方式',
        taskEditorPresentationDesc: '选择在桌面端编辑任务时的打开方式。',
        taskEditorPresentationInline: '侧边预览',
        taskEditorPresentationInlineDesc: '在当前视图内打开编辑器，适合快速编辑。',
        taskEditorPresentationModal: '弹窗',
        taskEditorPresentationModalDesc: '在居中的弹窗中打开编辑器，适合专注编辑。',
        taskEditorLayoutReset: '重置布局',
        taskEditorSection: '分组',
        taskEditorDefaultOpen: '默认展开的分组',
        taskEditorOpenByDefault: '默认展开',
        taskEditorDefaultOpenDesc: '让这些任务编辑分组在没有现有内容时也默认展开。',
        taskEditorFieldStatus: '状态',
        taskEditorFieldProject: '项目',
        taskEditorFieldSection: '分组',
        taskEditorFieldArea: '领域',
        taskEditorFieldPriority: '优先级',
        taskEditorFieldEnergyLevel: '精力水平',
        taskEditorFieldAssignedTo: '负责人',
        taskEditorFieldContexts: '情境',
        taskEditorFieldDescription: '描述',
        taskEditorFieldTags: '标签',
        taskEditorFieldTimeEstimate: '时间预估',
        taskEditorFieldRecurrence: '重复',
        taskEditorFieldStartTime: '开始日期',
        taskEditorFieldDueDate: '截止日期',
        taskEditorFieldReviewAt: '回顾日期',
        taskEditorFieldAttachments: '附件',
        taskEditorFieldChecklist: '清单',
        taskEditorFieldTextDirection: '文本方向',
        featurePriorities: '优先级',
        featurePrioritiesDesc: '为任务显示优先级标记。',
        featureTimeEstimates: '时间估算',
        featureTimeEstimatesDesc: '为时间管理添加时长估计。',
        featurePomodoro: '番茄钟',
        featurePomodoroDesc: '在聚焦视图中启用可选的番茄钟面板。',
        pomodoroCustomPreset: '自定义预设',
        pomodoroCustomPresetDesc: '添加一个额外的专注/休息预设。若与内置预设相同，将继续只显示内置选项。',
        pomodoroFocusMinutes: '专注分钟',
        pomodoroBreakMinutes: '休息分钟',
        pomodoroLinkTask: '将计时器关联到任务',
        pomodoroLinkTaskDesc: '在聚焦中显示计时任务选择器和完成任务操作。',
        pomodoroAutoStartBreaks: '自动开始休息',
        pomodoroAutoStartBreaksDesc: '当专注阶段结束时，自动开始休息计时。',
        pomodoroAutoStartFocus: '自动开始专注',
        pomodoroAutoStartFocusDesc: '当休息阶段结束时，自动开始下一轮专注计时。',
        notifications: '通知',
        notificationsDesc: '启用任务提醒与每日简报通知。',
        notificationsEnable: '启用通知',
        startDateNotifications: '开始日期提醒',
        startDateNotificationsDesc: '在任务开始日期/时间到达时提醒我。',
        dueDateNotifications: '截止日期提醒',
        dueDateNotificationsDesc: '在任务截止日期/时间到达时提醒我。',
        reviewAtNotifications: '回顾日期提醒',
        reviewAtNotificationsDesc: '在回顾（tickler）日期到期时提醒我。',
        ai: 'AI 助手',
        aiDesc: '帮助澄清与拆解任务（可选）。',
        aiEnable: '启用 AI 助手',
        aiProvider: '服务商',
        aiProviderOpenAI: 'OpenAI',
        aiProviderGemini: 'Gemini',
        aiProviderAnthropic: 'Anthropic（Claude）',
        aiModel: '模型',
        aiBaseUrl: '自定义 OpenAI 兼容基础 URL',
        aiBaseUrlHint: '官方 OpenAI 请留空。若使用本地或第三方 OpenAI 兼容接口，例如 llama.cpp、Ollama、LM Studio、GLM 或 vLLM，请在这里填写。',
        aiBaseUrlModelHint: '这个模型看起来不是官方 OpenAI 模型。如果你在使用 GLM 或其他 OpenAI 兼容服务，请设置自定义基础 URL。',
        aiApiKey: 'API 密钥',
        aiApiKeyHint: '仅保存在本机，不会同步。官方 OpenAI 必须填写密钥。自定义 OpenAI 兼容端点也可能需要密钥；仅当该端点允许匿名访问时才可留空。',
        aiReasoning: '推理强度',
        aiReasoningHint: '仅用于 GPT-5 模型。',
        aiEffortLow: '低',
        aiEffortMedium: '中',
        aiEffortHigh: '高',
        aiCopilotModel: '助手模型',
        aiCopilotHint: '用于快速补全建议。',
        aiConsentTitle: '启用 AI 功能？',
        aiConsentDescription: '要使用此功能，您的任务数据将发送到 {provider} 进行处理。该数据受其隐私政策约束。Mindwtr 不会收集这些数据。是否继续？',
        aiConsentCancel: '取消',
        aiConsentAgree: '同意',
        aiThinkingBudget: '思考预算',
        aiThinkingHint: '仅用于 Claude/Gemini。0 代表关闭深度思考。',
        aiThinkingEnable: '启用思考',
        aiThinkingEnableDesc: '为复杂任务启用扩展推理。',
        aiThinkingOff: '关闭',
        aiThinkingLow: '低',
        aiThinkingMedium: '中',
        aiThinkingHigh: '高',
        speechTitle: '语音转文字',
        speechDesc: '转录语音并映射到任务字段。',
        speechEnable: '启用语音转文字',
        speechProvider: '语音服务商',
        speechProviderOffline: '本地（Whisper）',
        speechModel: '语音模型',
        speechOfflineModel: '离线模型',
        speechOfflineModelDesc: '下载一次即可离线转录。',
        speechOfflineReady: '模型已下载',
        speechOfflineNotDownloaded: '尚未下载模型',
        speechOfflineDownload: '下载',
        speechOfflineDownloadSuccess: '下载完成',
        speechOfflineDelete: '删除',
        speechOfflineDownloadError: '离线模型下载失败',
        speechLanguage: '语音语言',
        speechLanguageHint: '可填写语言名称或代码，留空则自动检测。',
        speechLanguageAuto: '自动检测语言',
        speechMode: '处理模式',
        speechModeHint: '智能解析可提取日期与字段，纯转录仅输出文本。',
        speechModeSmart: '智能解析',
        speechModeTranscript: '仅转录',
        speechFieldStrategy: '字段映射',
        speechFieldStrategyHint: '选择默认写入标题或描述的位置。',
        speechFieldSmart: '智能',
        speechFieldTitle: '标题',
        speechFieldDescription: '描述',
        dailyDigest: '每日简报',
        dailyDigestDesc: '早间简报与晚间回顾提醒。',
        dailyDigestMorning: '早间简报',
        dailyDigestEvening: '晚间回顾',
        weeklyReview: '每周回顾',
        weeklyReviewDesc: '在你设定的时间提醒进行每周回顾。',
        weeklyReviewDay: '回顾日期',
        weeklyReviewTime: '回顾时间',
        weeklyReviewConfig: '每周回顾流程',
        weeklyReviewConfigDesc: '配置每周回顾中显示哪些步骤。',
        weeklyReviewIncludeContextsStep: '包含情境步骤',
        weeklyReviewIncludeContextsStepDesc: '在“等待中”和“项目”之间显示专门的情境回顾步骤。',
        on: '开启',
        off: '关闭',
        visible: '显示',
        hidden: '隐藏',
        manage: '管理',
        dataTransfer: '数据传输',
        dataTransferDesc: '导出完整备份、从备份恢复本地数据，或导入 Todoist、DGT GTD 与 OmniFocus 导出文件。',
        exportBackup: '导出备份',
        exportBackupDesc: '将当前本地数据保存为 JSON 备份文件。',
        restoreBackup: '恢复备份',
        restoreBackupDesc: '从 Mindwtr 备份 JSON 文件替换本地数据。',
        importTodoist: '从 Todoist 导入',
        importTodoistDesc: '将 Todoist 的 CSV 或 ZIP 导出导入为 Mindwtr 项目。',
        importDgt: '从 DGT GTD 导入',
        importDgtDesc: '将 DGT GTD 的 JSON 或 ZIP 导出导入为 Mindwtr 的领域、项目和任务。',
        importOmniFocus: '从 OmniFocus 导入',
        importOmniFocusDesc: '将 OmniFocus 的 CSV、JSON 或 ZIP 导出导入为 Mindwtr 项目和收集箱任务。',
        diagnostics: '诊断',
        diagnosticsDesc: '帮助排查问题。',
        analyticsHeartbeat: '匿名使用心跳',
        analyticsHeartbeatDesc: '每天发送一个很小的诊断信号，用于了解应用健康状况以及平台和版本使用情况。不包含任务或个人数据。',
        analyticsHeartbeatDisableTitle: '关闭匿名心跳？',
        analyticsHeartbeatDisableDesc: '心跳不包含任务、项目、笔记、文件、AI 提示词、邮箱、姓名、联系人或账户数据。它帮助了解活跃平台和版本。关闭后，Mindwtr 将停止从此安装发送心跳请求。',
        analyticsHeartbeatDisableConfirm: '关闭',
        analyticsHeartbeatKeepEnabled: '保持开启',
        debugLogging: '调试日志',
        debugLoggingDesc: '将错误记录到本地以便提交反馈。',
        logFile: '日志文件',
        clearLog: '清除日志',
        sync: '同步',
        syncDescription:
            '配置一个辅助文件夹来同步您的数据（如 Dropbox、Syncthing）。若需要更实时的多设备同步，建议优先使用 WebDAV。',
        syncBackend: '同步后端',
        syncBackendOff: '关闭',
        syncBackendFile: '文件',
        syncBackendWebdav: 'WebDAV',
        syncBackendCloud: '云端',
        syncBackendCloudkit: 'iCloud',
        syncPreferences: '设置同步选项',
        syncPreferencesDesc: '选择要在设备间同步的偏好设置。',
        syncPreferenceAppearance: '外观（主题、密度、文字大小、任务年龄）',
        syncPreferenceLanguage: '语言与日期格式',
        syncPreferenceGtd: '日程默认值',
        syncPreferenceSavedFilters: '已保存筛选',
        syncPreferenceExternalCalendars: '外部日历 URL',
        syncPreferenceAi: 'AI 设置（模型、提供商）',
        syncPreferenceAiHint: 'API 密钥和本地模型路径不会同步。',
        backgroundSync: '后台同步',
        backgroundSyncDesc: '桌面端会在 Mindwtr 运行时每 15 分钟同步一次。关闭到托盘可保持运行；开机自动启动可在登录后启动。退出应用会停止桌面后台同步。',
        attachmentsCleanup: '附件清理',
        attachmentsCleanupDesc: '从设备和同步存储中删除已删除或孤立的附件文件。',
        attachmentsCleanupLastRun: '上次清理',
        attachmentsCleanupNever: '从未',
        attachmentsCleanupPendingDeletes: '待处理远程删除',
        attachmentsCleanupPendingDeletesClear: '清除待处理删除',
        attachmentsCleanupPendingDeletesConfirm: '仅当你不再希望 Mindwtr 从旧同步后端删除这些文件时才清除。此操作不会删除任何文件。',
        attachmentsCleanupPendingDeletesConfirmTitle: '清除待处理的附件删除？',
        attachmentsCleanupRun: '立即清理',
        attachmentsCleanupRunning: '清理中...',
        calendar: '日历',
        calendarDesc: '通过 ICS 订阅地址或本地 .ics 文件查看外部日历（只读）。',
        externalCalendars: '外部日历',
        calendarName: '名称',
        calendarUrl: 'ICS 地址',
        calendarAdd: '添加日历',
        calendarChooseLocalFile: '选择本地 .ics 文件',
        calendarRemove: '移除',
        calendarSystemTitle: 'Apple 日历（macOS）',
        calendarSystemDesc: '通过 EventKit 读取 macOS 已同步的 Apple 日历账户（iCloud、Google、Exchange）事件。',
        calendarSystemStatus: 'Apple 日历访问',
        calendarSystemPermissionGranted: '已授权',
        calendarSystemPermissionUndetermined: '未请求',
        calendarSystemPermissionDenied: '已拒绝',
        calendarSystemPermissionUnsupported: '不支持',
        calendarSystemRequestAccess: '请求访问',
        calendarSystemDeniedHint: '日历访问被拒绝。请在 macOS 系统设置 > 隐私与安全性 > 日历 中为 Mindwtr 开启权限。',
        syncFolderLocation: '同步文件夹',
        savePath: '保存',
        browse: '浏览…',
        syncNow: '立即同步',
        syncing: '同步中…',
        syncQueued: '同步已排队',
        pathHint: '请选择文件夹（如 ~/Sync/mindwtr）。使用 Syncthing 时建议开启 Send & Receive 与 Watch for Changes，并在切换设备前手动点“立即同步”。',
        webdavUrl: 'WebDAV 地址',
        webdavUsername: '用户名',
        webdavPassword: '密码',
        webdavSave: '保存 WebDAV',
        testConnection: '测试连接',
        webdavTestHint: '仅验证地址和凭据，不执行数据同步',
        webdavTestAccessibility: '测试 WebDAV 连接',
        webdavHint: '请输入同步文件夹地址，Mindwtr 会在其中存放 data.json（例如 https://example.com/remote.php/dav/files/user/mindwtr）。',
        allowInsecureHttp: '允许不安全连接（HTTP）',
        allowInsecureHttpHint: '仅允许本机或私有网络 HTTP。数据将以未加密方式传输。',
        cloudUrl: '自托管地址',
        cloudToken: '访问令牌',
        cloudSave: '保存自托管配置',
        cloudHint: '请输入自托管基础地址（例如 https://example.com 或 https://example.com/mindwtr），Mindwtr 会自动追加 /v1/data。',
        cloudProvider: '云服务提供方',
        cloudProviderSelfHosted: '自托管',
        cloudProviderDropbox: 'Dropbox',
        cloudProviderCloudkit: 'iCloud',
        cloudkitDesc: '通过 iCloud 在 Apple 设备间同步您的任务、项目和领域。无需额外设置。',
        dropboxAppKey: 'Dropbox 账号',
        dropboxAppKeyHint: 'Dropbox App Key 在构建/发布时注入。',
        dropboxRedirectUri: '回调地址',
        dropboxStatus: '状态',
        dropboxConnected: '已连接',
        dropboxNotConnected: '未连接',
        dropboxConnect: '连接 Dropbox',
        dropboxDisconnect: '断开 Dropbox',
        dropboxTest: '测试连接',
        dropboxTestReachable: '可访问',
        dropboxTestFailed: '失败',
        obsidianVault: 'Obsidian 资料库',
        obsidianVaultDesc: '连接本地 Obsidian 资料库，并将 Markdown 复选框任务作为只读外部任务导入。',
        obsidianEnable: '启用 Obsidian 集成',
        obsidianVaultPath: '资料库文件夹',
        obsidianVaultPathHint: '选择资料库根目录。Mindwtr 会从配置的扫描文件夹读取 Markdown 笔记。',
        obsidianScanFolders: '扫描文件夹',
        obsidianScanFoldersHint: '每行填写一个相对文件夹。使用 / 扫描整个资料库。',
        obsidianInboxFile: 'Mindwtr 收件箱笔记',
        obsidianInboxFileHint: '用于从 Mindwtr 创建任务的相对 Markdown 路径。缺失的父目录会在需要时自动创建。',
        obsidianTaskNotes: 'TaskNotes',
        obsidianTaskNotesDesc: '自动检测 TaskNotes 文件。这里仅控制是否包含归档任务，以及 Mindwtr 创建新任务时使用的格式。',
        obsidianTaskNotesIncludeArchived: '包含已归档的 TaskNotes',
        obsidianTaskNotesIncludeArchivedHint: '关闭后，已归档的 TaskNotes 文件不会出现在导入任务列表中。',
        obsidianNewTaskFormat: '新任务格式',
        obsidianNewTaskFormatHint: '自动模式会跟随当前资料库检测到的格式。仅在你希望 Mindwtr 创建的任务使用不同格式时再覆盖。',
        obsidianNewTaskFormatAuto: '自动检测',
        obsidianNewTaskFormatInline: '内联复选框',
        obsidianNewTaskFormatTaskNotes: 'TaskNotes 笔记',
        obsidianWatching: '正在监听资料库变更。',
        obsidianWatcherUnavailable: '实时更新不可用。',
        obsidianSave: '保存 Obsidian 设置',
        obsidianRemove: '断开资料库',
        obsidianRescan: '重新扫描资料库',
        obsidianRescanning: '正在扫描资料库...',
        obsidianLastScanned: '上次 Obsidian 扫描',
        obsidianNeverScanned: '从未扫描',
        obsidianMissingMarker: '该文件夹不包含 .obsidian 目录。如果你的资料库布局比较特殊，仍然可以保存。',
        obsidianChooseVaultFailed: '选择 Obsidian 资料库文件夹失败。',
        obsidianSaveFailed: '保存 Obsidian 配置失败。',
        obsidianRemoveFailed: '移除 Obsidian 配置失败。',
        obsidianScanFailed: '扫描 Obsidian 资料库失败。',
        obsidianScanSuccess: 'Obsidian 资料库扫描完成。',
        lastSync: '上次同步',
        lastSyncNever: '从未同步',
        lastSyncSuccess: '同步完成',
        lastSyncError: '同步失败',
        lastSyncConflict: '已解决冲突',
        lastSyncConflicts: '冲突',
        lastSyncSkew: '时钟偏差',
        lastSyncAdjusted: '时间修正',
        lastSyncConflictIds: '冲突 ID',
        syncHistory: '同步历史',
        recoverySnapshots: '恢复快照',
        recoverySnapshotsDesc: '同步前创建。最多保留 7 天（最多 5 个文件）。',
        recoverySnapshotsLoading: '正在加载快照…',
        recoverySnapshotsEmpty: '暂无快照。',
        recoverySnapshotsRestore: '恢复',
        recoverySnapshotsConfirm: '恢复快照 {snapshot}？这将替换当前本地数据。',
        recoverySnapshotsConfirmTitle: '恢复快照？',
        recoverySnapshotsConfirmCancel: '取消',
        about: '关于',
        version: '版本',
        installChannel: '安装渠道',
        developer: '开发者',
        website: '开发者网站',
        github: 'GitHub',
        documentation: '文档',
        sponsorProject: '赞助项目',
        license: '许可证',
        checkForUpdates: '检查更新',
        checkStoreUpdates: '检查 Microsoft Store 更新',
        checking: '检查中…',
        upToDate: '您正在使用最新版本！',
        updateAvailable: '有可用更新',
        checkFailed: '检查更新失败',
        storeUpdateHint: '更新由 Microsoft Store 管理。',
        download: '下载',
        downloadStarting: '正在打开下载…',
        downloadStarted: '已在浏览器开始下载。',
        downloadFailed: '打开下载链接失败。',
        downloadChecksumMismatch: '校验和验证失败，请从发布页面重新下载。',
        downloadRecommended: '推荐下载包',
        downloadAURHint: '检测到 Arch：建议使用 AUR 更新',
        changelog: '更新日志',
        noChangelog: '暂无更新日志',
        later: '稍后',
        linuxUpdateHint: 'Linux 上无法自动安装更新。下载后请使用包管理器更新（如 yay -S mindwtr 或 paru -S mindwtr），或安装下载的包。',
        saved: '设置已保存',
        selectSyncFolderTitle: '选择同步文件夹',
        selectObsidianVaultTitle: '选择 Obsidian 资料库',
        system: '系统',
        light: '浅色',
        dark: '深色',
        eink: '电子墨水',
        nord: 'Nord',
        sepia: '复古米黄',
    },
} as const;

export type SettingsLabels = Record<keyof typeof labelFallback.en, string>;

export const labelKeyOverrides: Partial<Record<keyof SettingsLabels, string>> = {
    back: 'common.back',
    inboxModeGuided: 'process.modeGuided',
    inboxModeQuick: 'process.modeQuick',
    keybindings: 'keybindings.helpTitle',
    keybindingsDesc: 'settings.keybindingsDesc',
    keybindingVim: 'keybindings.style.vim',
    keybindingEmacs: 'keybindings.style.emacs',
    viewShortcuts: 'keybindings.openHelp',
    dateFormat: 'settings.dateFormat',
    dateFormatSystem: 'settings.dateFormatSystem',
    dateFormatDmy: 'settings.dateFormatDmy',
    dateFormatMdy: 'settings.dateFormatMdy',
    dateFormatYmd: 'settings.dateFormatYmd',
    timeFormat: 'settings.timeFormat',
    timeFormatSystem: 'settings.timeFormatSystem',
    timeFormat12h: 'settings.timeFormat12h',
    timeFormat24h: 'settings.timeFormat24h',
    taskEditorLayoutReset: 'settings.resetToDefault',
    autoArchiveDayUnit: 'common.days',
    taskEditorFieldStatus: 'taskEdit.statusLabel',
    taskEditorFieldProject: 'taskEdit.projectLabel',
    taskEditorFieldSection: 'taskEdit.sectionLabel',
    taskEditorFieldArea: 'taskEdit.areaLabel',
    taskEditorFieldPriority: 'taskEdit.priorityLabel',
    taskEditorFieldEnergyLevel: 'taskEdit.energyLevel',
    taskEditorFieldAssignedTo: 'taskEdit.assignedTo',
    taskEditorFieldContexts: 'taskEdit.contextsLabel',
    taskEditorFieldDescription: 'taskEdit.descriptionLabel',
    taskEditorFieldTags: 'taskEdit.tagsLabel',
    taskEditorFieldTimeEstimate: 'taskEdit.timeEstimateLabel',
    taskEditorFieldRecurrence: 'taskEdit.recurrenceLabel',
    taskEditorFieldStartTime: 'taskEdit.startDateLabel',
    taskEditorFieldDueDate: 'taskEdit.dueDateLabel',
    taskEditorFieldReviewAt: 'taskEdit.reviewDateLabel',
    taskEditorFieldAttachments: 'attachments.title',
    taskEditorFieldChecklist: 'taskEdit.checklist',
    taskEditorFieldTextDirection: 'taskEdit.textDirectionLabel',
} as const;
