export const labelFallback = {
    en: {
        title: 'Settings',
        general: 'General',
        integrations: 'Integrations',
        advanced: 'Advanced',
        subtitle: 'Customize your Mindwtr experience',
        searchPlaceholder: 'Search settings…',
        back: 'Back',
        features: 'Features',
        featuresDesc: 'Optional signals you can turn on when needed.',
        lookAndFeel: 'Look & Feel',
        localization: 'Localization',
        input: 'Input',
        windowBehavior: 'Window Behavior',
        appearance: 'Appearance',
        density: 'Density',
        densityDesc: 'Adjust list spacing to show more items on screen.',
        densityComfortable: 'Comfortable',
        densityCompact: 'Compact',
        textSize: 'Text size',
        textSizeDesc: 'Adjust interface text across the desktop app.',
        textSizeSmall: 'Small',
        textSizeDefault: 'Default',
        textSizeLarge: 'Large',
        textSizeExtraLarge: 'Extra large',
        showTaskAge: 'Show task age',
        showTaskAgeDesc: 'Display how long ago a task was created in task metadata.',
        gtd: 'GTD',
        gtdDesc: 'Mindwtr works out of the box. Tune these defaults only when you want a different GTD flow.',
        inboxProcessing: 'Inbox processing',
        inboxProcessingDesc: 'Customize the inbox workflow to match your style.',
        inboxDefaultMode: 'Default mode',
        inboxModeGuided: 'Guided',
        inboxModeQuick: 'Quick',
        inboxTwoMinuteEnabled: 'Show the 2-minute shortcut',
        inboxTwoMinuteFirst: 'Ask the 2-minute rule first',
        inboxProjectFirst: 'Ask for project early',
        inboxContextStepEnabled: 'Include Contexts & Tags step',
        inboxScheduleEnabled: 'Allow scheduling during processing',
        inboxReferenceEnabled: 'Offer Reference during processing',
        captureDefault: 'Default capture method',
        captureDefaultDesc: 'Choose whether quick capture starts with text or audio.',
        captureDefaultText: 'Text',
        captureDefaultAudio: 'Audio',
        captureSaveAudio: 'Save audio attachments',
        captureSaveAudioDesc: 'Keep the audio file attached after transcription.',
        quickAddAutoClean: 'Clean up quick add text',
        quickAddAutoCleanDesc: 'Remove recognized dates, tags, and contexts from the title after applying them. Off keeps your text exactly as typed.',
        markdownEditorAssist: 'Editor typing help',
        markdownEditorAssistDesc: 'Auto-pair brackets, continue lists, link pasted URLs, and suggest references while editing descriptions. Off makes them plain-text fields with nothing inserted.',
        autoArchive: 'Auto-archive done tasks',
        autoArchiveDesc: 'Move completed tasks to Archived after a set number of days.',
        autoArchiveNever: 'Never (keep in Done)',
        autoArchiveDayUnit: 'days',
        defaultScheduleTime: 'Default schedule time',
        defaultScheduleTimeDesc: 'Optional. Pre-fills manual Start, Due, and Review time fields after you choose a date. Leave blank for date-only.',
        defaultArea: 'Default area for new tasks',
        defaultAreaDesc: 'Applies to new tasks, including Inbox captures. You can still change or clear the area per task.',
        defaultAreaNone: 'No area',
        defaultAreaActive: 'Current area filter',
        focusTaskLimit: "Today's focus limit",
        focusTaskLimitDesc: "Maximum tasks you can star for today's focus.",
        defaultProjectFlowMode: 'Default project flow',
        defaultProjectFlowModeDesc: 'Applies only when creating new projects. Existing projects keep their current flow.',
        projectFlowParallel: 'Parallel',
        projectFlowSequential: 'Sequential',
        language: 'Language',
        weekStart: 'Week starts on',
        weekStartSunday: 'Sunday',
        weekStartSystem: 'System default',
        weekStartMonday: 'Monday',
        weekStartSaturday: 'Saturday',
        dateFormat: 'Date format',
        dateFormatSystem: 'System default',
        dateFormatDmy: 'Day / Month / Year',
        dateFormatMdy: 'Month / Day / Year',
        dateFormatYmd: 'Year / Month / Day',
        calendarSystem: 'Calendar system',
        calendarSystemGregorian: 'Gregorian',
        calendarSystemJalali: 'Jalali (Solar Hijri)',
        timeFormat: 'Time format',
        timeFormatSystem: 'System default',
        timeFormat12h: '12-hour',
        timeFormat24h: '24-hour',
        keybindings: 'Keyboard Shortcuts',
        keybindingsDesc: 'Choose your preferred desktop keybinding style.',
        undoNotifications: 'Undo notifications',
        undoNotificationsDesc: 'Show an Undo toast after marking tasks Done or deleting tasks.',
        globalQuickAddShortcut: 'Global quick add shortcut',
        globalQuickAddShortcutDesc: 'Used system-wide for quick capture, even when Mindwtr is not focused.',
        globalQuickAddFlatpakDesc: 'Flatpak/Wayland does not allow Mindwtr to own this shortcut directly.',
        globalQuickAddFlatpakCommand: 'Flatpak custom shortcut command',
        globalQuickAddFlatpakCommandDesc: 'Bind this command in your desktop shortcut settings.',
        keybindingStandard: 'Standard',
        keybindingVim: 'Vim',
        keybindingEmacs: 'Emacs',
        viewShortcuts: 'View shortcuts',
        windowDecorations: 'Window decorations',
        windowDecorationsDesc: 'Show system title bar and window borders.',
        closeBehavior: 'Close window behavior',
        closeBehaviorDesc: 'Choose what happens when you close the window.',
        closeBehaviorAsk: 'Ask every time',
        closeBehaviorTray: 'Keep running in tray',
        closeBehaviorQuit: 'Quit the app',
        launchAtStartup: 'Launch at startup',
        launchAtStartupDesc: 'Start Mindwtr automatically when you sign in to this computer.',
        showTray: 'Show system tray icon',
        showTrayDesc: 'Display the app icon in your system tray for quick access.',
        automation: 'Automation',
        rendering: 'Rendering',
        softwareRendering: 'Use software rendering',
        softwareRenderingDesc: 'Requires restart. Use only for blank windows, flicker, or GPU driver problems.',
        network: 'Network',
        localApiServer: 'Enable local API server',
        localApiPort: 'Port',
        localApiPortDesc: 'Localhost only. Default: 3456.',
        localApiToken: 'Bearer token',
        localApiTokenDesc: 'Required in the Authorization header for every request.',
        localApiSecurityNote: 'Local apps and scripts with this token can read and change Mindwtr data.',
        localApiStopped: 'Off',
        localApiUnavailable: 'Desktop app only',
        localApiPortInvalid: 'Enter a port between 1024 and 65535.',
        taskEditorLayout: 'Task editor layout',
        taskEditorLayoutDesc: 'Choose which fields are shown by default in the task editor, including Priority and Time estimate.',
        taskEditorLayoutHint: 'Hidden fields appear when they have content or after clicking "More options".',
        taskEditorPresentation: 'Editor opening',
        taskEditorPresentationDesc: 'Choose how task editing opens when you use the desktop editor.',
        taskEditorPresentationInline: 'Side peek',
        taskEditorPresentationInlineDesc: 'Open the editor inline inside the current view for faster quick edits.',
        taskEditorPresentationModal: 'Pop-up',
        taskEditorPresentationModalDesc: 'Open the editor in a centered modal for focused editing.',
        taskEditorLayoutReset: 'Reset layout',
        taskEditorSection: 'Section',
        taskEditorDefaultOpen: 'Default-open sections',
        taskEditorOpenByDefault: 'Open by default',
        taskEditorDefaultOpenDesc: 'Keep these task editor sections expanded whenever they do not already have content.',
        taskEditorFieldStatus: 'Status',
        taskEditorFieldProject: 'Project',
        taskEditorFieldSection: 'Project section',
        taskEditorFieldArea: 'Area',
        taskEditorFieldPriority: 'Priority',
        taskEditorFieldEnergyLevel: 'Energy level',
        taskEditorFieldAssignedTo: 'Assigned to',
        taskEditorFieldContexts: 'Contexts',
        taskEditorFieldDescription: 'Description',
        taskEditorFieldLocation: 'Location',
        taskEditorFieldTags: 'Tags',
        taskEditorFieldTimeEstimate: 'Time estimate',
        taskEditorFieldRecurrence: 'Recurrence',
        taskEditorFieldStartTime: 'Start date',
        taskEditorFieldDueDate: 'Due date',
        taskEditorFieldReviewAt: 'Review date',
        taskEditorFieldAttachments: 'Attachments',
        taskEditorFieldChecklist: 'Checklist',
        taskEditorFieldTextDirection: 'Text direction',
        featurePriorities: 'Priorities',
        featurePrioritiesDesc: 'Show a priority flag on tasks.',
        featureTimeEstimates: 'Time estimates',
        featureTimeEstimatesDesc: 'Add quick duration estimates for time blocking.',
        featurePomodoro: 'Pomodoro timer',
        featurePomodoroDesc: 'Enable the optional Pomodoro panel in Focus view.',
        pomodoroCustomPreset: 'Custom preset',
        pomodoroCustomPresetDesc: 'Add one extra focus/break preset. Matching a built-in preset keeps the built-in chips only.',
        pomodoroFocusMinutes: 'Focus minutes',
        pomodoroBreakMinutes: 'Break minutes',
        pomodoroLinkTask: 'Link timer to task',
        pomodoroLinkTaskDesc: 'Show the Timer task picker and Task done action in Focus.',
        pomodoroAutoStartBreaks: 'Auto-start breaks',
        pomodoroAutoStartBreaksDesc: 'Start the break timer automatically when a focus session ends.',
        pomodoroAutoStartFocus: 'Auto-start focus',
        pomodoroAutoStartFocusDesc: 'Start the next focus session automatically when a break ends.',
        notifications: 'Notifications',
        notificationsDesc: 'Enable task reminders and daily digest notifications.',
        notificationsEnable: 'Enable notifications',
        startDateNotifications: 'Start date reminders',
        startDateNotificationsDesc: 'Notify me when a task start date/time arrives.',
        dueDateNotifications: 'Due date reminders',
        dueDateNotificationsDesc: 'Notify me when a task due date/time arrives.',
        reviewAtNotifications: 'Review date reminders',
        reviewAtNotificationsDesc: 'Notify me when a review (tickler) date is due.',
        ai: 'AI Assistant',
        aiDesc: 'Optional help to clarify and break down tasks.',
        aiUsageTitle: 'Where and how to use AI',
        aiUsageClarify: 'Clarify: open a task, click the ✨ sparkle button in its editor, and choose Clarify to turn a vague task into a clear next action.',
        aiUsageBreakdown: 'Break down: in that same ✨ menu, choose Break down to split a task or project into concrete steps.',
        aiUsageSuggestions: 'Suggestions: as you type a task title or notes, a ✨ suggestion for context, time estimate, and tags appears below — click it to apply.',
        aiUsageReview: 'Weekly review: open the Weekly Review, go to the AI step, and click Run to get suggested actions for stale tasks.',
        aiEnable: 'Enable AI assistant',
        aiProvider: 'Provider',
        aiProviderOpenAI: 'OpenAI',
        aiProviderGemini: 'Gemini',
        aiProviderAnthropic: 'Anthropic (Claude)',
        aiModel: 'Model',
        aiBaseUrl: 'Custom OpenAI-compatible base URL',
        aiBaseUrlHint: 'Leave blank for official OpenAI. Set this for local or third-party OpenAI-compatible APIs such as llama.cpp, Ollama, LM Studio, GLM, or vLLM.',
        aiBaseUrlModelHint: 'This model looks non-OpenAI. If you are using GLM or another OpenAI-compatible provider, set a custom base URL.',
        aiExtraBodyParams: 'Extra request parameters',
        aiExtraBodyParamsDesc: 'Optional JSON object merged into OpenAI-compatible requests.',
        aiExtraBodyParamsHint: 'Core fields such as model, messages, and response_format are protected. Example: { "thinking": { "type": "disabled" } }',
        aiExtraBodyParamsInvalid: 'Enter a valid JSON object.',
        aiExtraBodyParamsSave: 'Save parameters',
        aiApiKey: 'API key',
        aiApiKeyHint: 'Stored locally on this device. Never synced. Official OpenAI requires a key. Custom OpenAI-compatible endpoints may also require one; leave it blank only if your endpoint allows unauthenticated requests.',
        aiReasoning: 'Reasoning effort',
        aiReasoningHint: 'Used by GPT-5 models.',
        aiEffortLow: 'Low',
        aiEffortMedium: 'Medium',
        aiEffortHigh: 'High',
        aiCopilotModel: 'Copilot model',
        aiCopilotHint: 'Used for fast autocomplete suggestions.',
        aiConsentTitle: 'Enable AI Features?',
        aiConsentDescription: 'To use this feature, your task data will be sent to {provider} for processing. This data is subject to their privacy policy. Mindwtr does not collect this data. Do you wish to proceed?',
        aiConsentCancel: 'Cancel',
        aiConsentAgree: 'Agree',
        aiThinkingBudget: 'Thinking budget',
        aiThinkingHint: 'Claude/Gemini only. 0 disables extended thinking.',
        aiThinkingEnable: 'Enable thinking',
        aiThinkingEnableDesc: 'Use extended reasoning for complex tasks.',
        aiThinkingOff: 'Off',
        aiThinkingLow: 'Low',
        aiThinkingMedium: 'Medium',
        aiThinkingHigh: 'High',
        speechTitle: 'Speech to text',
        speechDesc: 'Transcribe voice captures and map them into task fields.',
        speechEnable: 'Enable speech to text',
        speechProvider: 'Speech provider',
        speechProviderOffline: 'On-device (Whisper)',
        speechProviderParakeet: 'Parakeet v3 experimental',
        speechModel: 'Speech model',
        speechOfflineModel: 'Offline model',
        speechOfflineModelDesc: 'Download once to transcribe fully offline.',
        speechParakeetModelDesc: 'Download once to install the Parakeet ASR model for local transcription. Model weights are not bundled with Mindwtr.',
        speechParakeetModelPath: 'Install folder',
        speechParakeetModelPathPlaceholder: 'App data folder',
        speechOfflineReady: 'Model downloaded',
        speechOfflineNotDownloaded: 'Model not downloaded',
        speechOfflineEstimatedSize: 'Estimated download size',
        speechOfflinePathSet: 'Model path set',
        speechOfflineDownload: 'Download',
        speechOfflineDownloadSuccess: 'Download complete',
        speechOfflineDelete: 'Delete',
        speechOfflineDownloadRuntime: 'Downloading runtime',
        speechOfflineDownloadModel: 'Downloading model',
        speechOfflineInstalling: 'Installing',
        speechOfflineDownloadError: 'Offline model download failed',
        speechLanguage: 'Audio language',
        speechLanguageHint: 'Use a language name or code, or leave blank to auto-detect.',
        speechLanguageAuto: 'Auto (detect language)',
        speechMode: 'Processing mode',
        speechModeHint: 'Smart parse extracts dates and fields; transcript-only just transcribes.',
        speechModeSmart: 'Smart parse',
        speechModeTranscript: 'Transcript only',
        speechFieldStrategy: 'Field mapping',
        speechFieldStrategyHint: 'Choose where the transcript should land by default.',
        speechFieldSmart: 'Smart',
        speechFieldTitle: 'Title',
        speechFieldDescription: 'Description',
        dailyDigest: 'Daily Digest',
        dailyDigestDesc: 'Morning briefing and evening review prompts.',
        dailyDigestMorning: 'Morning briefing',
        dailyDigestEvening: 'Evening review',
        weeklyReview: 'Weekly review',
        weeklyReviewDesc: 'Get a weekly review reminder at your chosen time.',
        weeklyReviewDay: 'Review day',
        weeklyReviewTime: 'Review time',
        weeklyReviewConfig: 'Weekly review flow',
        weeklyReviewConfigDesc: 'Configure which steps appear in weekly review.',
        weeklyReviewIncludeContextsStep: 'Include Contexts step',
        weeklyReviewIncludeContextsStepDesc: 'Show a dedicated contexts review step between Waiting For and Projects.',
        on: 'On',
        off: 'Off',
        visible: 'Shown',
        hidden: 'Hidden',
        manage: 'Manage',
        dataTransfer: 'Data Transfer',
        dataTransferDesc: 'Export a full backup, restore local data from backup, or import Todoist, TickTick, DGT GTD, and OmniFocus exports.',
        exportBackup: 'Export Backup',
        exportBackupDesc: 'Save the current local data as a JSON backup file.',
        restoreBackup: 'Restore Backup',
        restoreBackupDesc: 'Replace local data from a Mindwtr backup JSON file.',
        importTodoist: 'Import from Todoist',
        importTodoistDesc: 'Import Todoist CSV or ZIP exports into Mindwtr projects.',
        importTickTick: 'Import from TickTick',
        importTickTickDesc: 'Import TickTick CSV or ZIP backups into Mindwtr areas, projects, and tasks.',
        importDgt: 'Import from DGT GTD',
        importDgtDesc: 'Import DGT GTD JSON or ZIP exports into Mindwtr areas, projects, and tasks.',
        importOmniFocus: 'Import from OmniFocus',
        importOmniFocusDesc: 'Import OmniFocus CSV, JSON, or ZIP exports into Mindwtr projects and inbox tasks.',
        diagnostics: 'Diagnostics',
        diagnosticsDesc: 'Help troubleshoot issues.',
        analyticsHeartbeat: 'Opt out of diagnostics',
        analyticsHeartbeatDesc: 'Diagnostics are anonymous and help improve Mindwtr. No task text, notes, or personal data. Turn this on to stop sending.',
        analyticsHeartbeatDisableTitle: 'Opt out of diagnostics?',
        analyticsHeartbeatDisableDesc: 'Turn this on to stop anonymous diagnostics. No task text, notes, or personal data is sent.',
        analyticsHeartbeatDisableConfirm: 'Opt out',
        analyticsHeartbeatKeepEnabled: 'Keep sending',
        debugLogging: 'Debug logging',
        debugLoggingDesc: 'Record errors locally to share with support.',
        logFile: 'Log file',
        clearLog: 'Clear log',
        sync: 'Sync',
        syncDescription:
            'Choose how Mindwtr syncs your data. Dropbox is one-click in supported builds; File works with local sync folders; WebDAV and Self-Hosted cover custom storage.',
        syncBackend: 'Sync backend',
        syncBackendOff: 'Off',
        syncBackendFile: 'File',
        syncBackendWebdav: 'WebDAV',
        syncBackendCloud: 'Self-Hosted',
        syncBackendCloudkit: 'iCloud',
        syncBackendChoiceHint: 'Choose one sync method. Turn sync off to keep data local to this device.',
        syncBackendGroupCloud: 'Cloud Sync',
        syncBackendGroupCloudDesc: 'Easy account sync handled by Mindwtr.',
        syncBackendGroupFile: 'Folder / File Sync',
        syncBackendGroupFileDesc: 'Bring your own local synced folder.',
        syncBackendGroupAdvanced: 'Advanced / Custom Server',
        syncBackendGroupAdvancedDesc: 'Use WebDAV or your own Mindwtr Cloud endpoint.',
        networkProxyUrl: 'Proxy URL',
        networkProxyUrlDesc: 'Optional desktop HTTP(S) proxy for sync and external calendar requests.',
        networkProxyUrlHint: 'Use http://host:port or https://host:port. Credentials may be included in the URL. This setting is not synced across devices.',
        networkProxyInvalid: 'Enter a valid http(s) proxy URL.',
        networkProxySave: 'Save proxy',
        syncPreferences: 'Settings sync options',
        syncPreferencesDesc: 'Choose which preferences stay in sync across devices.',
        syncPreferenceAppearance: 'Appearance (theme, density, text size, task age)',
        syncPreferenceLanguage: 'Language & date format',
        syncPreferenceGtd: 'Scheduling defaults',
        syncPreferenceSavedFilters: 'Saved filters',
        syncPreferenceExternalCalendars: 'External calendar URLs',
        syncPreferenceAi: 'AI settings (models, providers)',
        syncPreferenceAiHint: 'API keys and local model paths are never synced.',
        backgroundSync: 'Background sync',
        backgroundSyncDesc: 'Desktop sync runs on startup, when the app regains focus, every 15 minutes while Mindwtr is running, and shortly after task/project changes. Close-to-tray keeps it active; launch-at-startup can start it after sign-in. Quitting the app stops desktop background sync.',
        attachmentsCleanup: 'Attachment cleanup',
        attachmentsCleanupDesc: 'Remove deleted or orphaned attachment files from your device and sync storage.',
        attachmentsCleanupLastRun: 'Last cleanup',
        attachmentsCleanupNever: 'Never',
        attachmentsCleanupPendingDeletes: 'Pending remote deletes',
        attachmentsCleanupPendingDeletesClear: 'Clear pending deletes',
        attachmentsCleanupPendingDeletesConfirm: 'Only clear these if you no longer want Mindwtr to delete those files from the old sync backend. This does not delete any files.',
        attachmentsCleanupPendingDeletesConfirmTitle: 'Clear pending attachment deletes?',
        attachmentsCleanupRun: 'Run cleanup',
        attachmentsCleanupRunning: 'Cleaning...',
        calendar: 'Calendar',
        calendarDesc: 'View external calendars via ICS subscription URLs or local .ics files.',
        externalCalendars: 'External calendars',
        calendarName: 'Name',
        calendarUrl: 'ICS URL',
        calendarAdd: 'Add calendar',
        calendarChooseLocalFile: 'Choose local .ics file',
        calendarRemove: 'Remove',
        calendarSystemTitle: 'Apple Calendar (macOS)',
        calendarSystemDesc: 'Read events from Apple Calendar accounts synced by macOS (iCloud, Google, Exchange) via EventKit.',
        calendarSystemStatus: 'Apple Calendar access',
        calendarSystemPermissionGranted: 'Granted',
        calendarSystemPermissionUndetermined: 'Not requested',
        calendarSystemPermissionDenied: 'Denied',
        calendarSystemPermissionUnsupported: 'Unsupported',
        calendarSystemRequestAccess: 'Request access',
        calendarSystemDeniedHint: 'Calendar access is denied. Enable Mindwtr in macOS System Settings > Privacy & Security > Calendars.',
        calendarPushTitle: 'Push tasks to Apple Calendar',
        calendarPushDesc: 'Write scheduled tasks and tasks with due dates to a selected Apple Calendar. One-way only.',
        calendarPushEnable: 'Enable Apple Calendar push',
        calendarPushTarget: 'Sync target',
        calendarPushManagedTarget: 'Mindwtr calendar (created automatically)',
        calendarPushRefresh: 'Refresh calendars',
        calendarPushLoading: 'Loading...',
        calendarPushTargetHint: 'Use a dedicated Mindwtr calendar to avoid title prefixes in shared calendars.',
        syncFolderLocation: 'Sync folder',
        savePath: 'Save',
        browse: 'Browse…',
        syncNow: 'Sync now',
        syncing: 'Syncing…',
        syncQueued: 'Sync queued',
        pathHint: 'Choose a folder (e.g., ~/Sync/mindwtr). With Syncthing: use Send & Receive + Watch for Changes, then press Sync now before switching devices.',
        webdavUrl: 'WebDAV URL',
        webdavUsername: 'Username',
        webdavPassword: 'Password',
        webdavSave: 'Save WebDAV',
        testConnection: 'Test connection',
        webdavTestHint: 'Verify URL and credentials without syncing data',
        webdavTestAccessibility: 'Test WebDAV connection',
        webdavHint: 'Point to a folder — Mindwtr will store data.json inside (e.g., https://example.com/remote.php/dav/files/user/mindwtr).',
        allowInsecureHttp: 'Allow insecure connections (HTTP)',
        allowInsecureHttpHint: 'Only local or private-network HTTP is allowed. Data will be sent unencrypted.',
        cloudUrl: 'Self-hosted URL',
        cloudToken: 'Access token',
        cloudRememberToken: 'Remember token on this browser',
        cloudRememberTokenHint: 'Stores the token in localStorage so PWA sync works after reopening. Do not use on shared devices.',
        cloudSave: 'Save Self-Hosted',
        cloudHint: 'Use the base URL (e.g., https://example.com or https://example.com/mindwtr). Mindwtr will append /v1/data.',
        cloudProvider: 'Cloud provider',
        cloudProviderSelfHosted: 'Self-hosted',
        cloudProviderDropbox: 'Dropbox',
        cloudProviderCloudkit: 'iCloud',
        cloudkitDesc: 'Syncs your tasks, projects, and areas across Apple devices using iCloud. No setup required.',
        dropboxAppKey: 'Dropbox account',
        dropboxAppKeyHint: 'Dropbox app key is injected at build/release time.',
        dropboxRedirectUri: 'Redirect URI',
        dropboxStatus: 'Status',
        dropboxConnected: 'Connected',
        dropboxNotConnected: 'Not connected',
        dropboxConnect: 'Connect Dropbox',
        dropboxDisconnect: 'Disconnect Dropbox',
        dropboxTest: 'Test connection',
        dropboxTestReachable: 'Reachable',
        dropboxTestFailed: 'Failed',
        obsidianVault: 'Obsidian vault import',
        obsidianVaultDesc: 'Import tasks from a local Obsidian vault. Obsidian stays your notes and capture source; Mindwtr owns native commitments.',
        obsidianEnable: 'Enable Obsidian integration',
        obsidianVaultPath: 'Vault folder',
        obsidianVaultPathHint: 'Select the root folder of your vault. Mindwtr reads Markdown notes from the configured scan folders.',
        obsidianDetectedVaults: 'Detected vaults:',
        obsidianScanFolders: 'Scan folders',
        obsidianScanFoldersHint: 'One relative folder per line. Use / to scan the whole vault.',
        obsidianInboxFile: 'Mindwtr inbox note',
        obsidianInboxFileHint: 'Relative Markdown path for tasks created from Mindwtr. Parent folders are created when needed.',
        obsidianDataview: 'Dataview metadata',
        obsidianDataviewDesc: 'Optional compatibility for vaults that already use Dataview-style inline fields.',
        obsidianDataviewMetadata: 'Import Dataview fields',
        obsidianDataviewMetadataHint: 'Reads project::, context::, due::, scheduled::, priority::, and estimate:: fields. Mindwtr does not write these fields back.',
        obsidianTaskNotes: 'TaskNotes',
        obsidianTaskNotesDesc: 'TaskNotes files are detected automatically. Use these options to control archived imports and the format Mindwtr uses when it creates new vault tasks.',
        obsidianTaskNotesIncludeArchived: 'Include archived TaskNotes',
        obsidianTaskNotesIncludeArchivedHint: 'Leave this off to keep archived TaskNotes files out of the imported task list.',
        obsidianNewTaskFormat: 'New task format',
        obsidianNewTaskFormatHint: 'Auto follows the detected vault format. Use an override only if you want Mindwtr-created tasks to use a different format.',
        obsidianNewTaskFormatAuto: 'Auto-detect',
        obsidianNewTaskFormatInline: 'Inline checkbox',
        obsidianNewTaskFormatTaskNotes: 'TaskNotes note',
        obsidianWatching: 'Watching for vault changes.',
        obsidianWatcherUnavailable: 'Live updates unavailable.',
        obsidianSave: 'Save Obsidian settings',
        obsidianRemove: 'Disconnect vault',
        obsidianRescan: 'Rescan vault',
        obsidianRescanning: 'Scanning vault...',
        obsidianLastScanned: 'Last Obsidian scan',
        obsidianNeverScanned: 'Never scanned',
        obsidianMissingMarker: 'This folder does not contain a .obsidian directory. You can still save it if your vault layout is unconventional.',
        obsidianChooseVaultFailed: 'Failed to choose Obsidian vault folder.',
        obsidianSaveFailed: 'Failed to save Obsidian config.',
        obsidianRemoveFailed: 'Failed to remove Obsidian config.',
        obsidianScanFailed: 'Failed to scan Obsidian vault.',
        obsidianScanSuccess: 'Obsidian vault scanned.',
        lastSync: 'Last sync',
        lastSyncNever: 'Never',
        lastSyncSuccess: 'Sync completed',
        lastSyncError: 'Sync failed',
        lastSyncConflict: 'Conflicts resolved',
        lastSyncConflicts: 'Conflicts',
        lastSyncSkew: 'Clock skew',
        lastSyncAdjusted: 'Timestamp fixes',
        lastSyncConflictIds: 'Conflict IDs',
        syncConflictKeptThisDevice: "kept this device's version",
        syncConflictKeptOtherDevice: 'kept the synced version',
        syncConflictChanged: 'changed: {{fields}}',
        syncConflictDeleteRestore: 'delete vs. edit',
        syncConflictMore: '+{{count}} more resolved conflicts',
        syncHistory: 'Sync history',
        recoverySnapshots: 'Recovery snapshots',
        recoverySnapshotsDesc: 'Created before sync. Kept for up to 7 days (max 5 files).',
        recoverySnapshotsLoading: 'Loading snapshots…',
        recoverySnapshotsEmpty: 'No snapshots yet.',
        recoverySnapshotsRestore: 'Restore',
        recoverySnapshotsConfirm: 'Restore snapshot {snapshot}? This will replace current local data.',
        recoverySnapshotsConfirmTitle: 'Restore snapshot?',
        recoverySnapshotsConfirmCancel: 'Cancel',
        about: 'About',
        version: 'Version',
        installChannel: 'Install Channel',
        developer: 'Developer',
        website: 'Developer Website',
        github: 'GitHub',
        documentation: 'Documentation',
        sponsorProject: 'Support development',
        license: 'License',
        feedback: 'Send feedback',
        feedbackDesc: 'Report a bug or suggest a feature. No account needed.',
        feedbackCategory: 'Category',
        feedbackCategoryBug: 'Bug report',
        feedbackCategoryFeature: 'Feature request',
        feedbackCategoryOther: 'Other',
        feedbackMessage: 'Message',
        feedbackMessagePlaceholder: 'Tell us what happened or what would help.',
        feedbackMessagePlaceholderBug: 'What did you expect, and what happened instead? Steps to reproduce if you can.',
        feedbackMessagePlaceholderFeature: 'What are you trying to do, what gets in the way, and what would help?',
        feedbackMessagePlaceholderOther: 'Tell us what is on your mind.',
        feedbackWhere: 'Where did this happen?',
        feedbackWherePlaceholder: 'Select a screen or workflow (optional)',
        feedbackWhereMessagePrefix: 'Where',
        feedbackWhereInbox: 'Inbox',
        feedbackWhereFocus: 'Focus',
        feedbackWhereProjects: 'Projects',
        feedbackWhereReview: 'Review',
        feedbackWhereSettings: 'Settings',
        feedbackWhereSync: 'Sync',
        feedbackWhereImportExport: 'Import or export',
        feedbackWhereNotifications: 'Notifications',
        feedbackWhereOther: 'Other',
        feedbackEmail: 'Reply email (optional)',
        feedbackEmailPlaceholder: 'you@example.com',
        feedbackIncludeDiagnostics: 'Include recent diagnostics',
        feedbackIncludeDiagnosticsDesc: 'Adds recent sanitized app logs. Task data, backups, and screenshots are not attached.',
        feedbackPrivacy: 'This sends your message, app version, platform, and diagnostics only if you choose to include them. A reply email is sent only if you enter one. Task content is not attached.',
        feedbackSubmit: 'Send feedback',
        feedbackSending: 'Sending...',
        feedbackSent: 'Feedback sent. Thank you.',
        feedbackFailed: 'Could not send feedback. Your message is still here; please try again.',
        feedbackUnavailable: 'Feedback is not configured in this build.',
        feedbackUnavailableDesc: 'You can still report bugs and feature requests with the GitHub issue templates.',
        feedbackOpenGitHubIssue: 'Open GitHub issue',
        feedbackRequired: 'Add a short message first.',
        feedbackInvalidEmail: 'Enter a valid email or leave it blank.',
        checkForUpdates: 'Check for Updates',
        checkStoreUpdates: 'Check Microsoft Store',
        checking: 'Checking…',
        upToDate: 'You are using the latest version!',
        updateAvailable: 'Update Available',
        checkFailed: 'Failed to check for updates',
        storeUpdateHint: 'Updates are managed by Microsoft Store.',
        download: 'Download',
        downloadStarting: 'Opening download…',
        downloadStarted: 'Download started in your browser.',
        downloadFailed: 'Failed to open download link.',
        downloadChecksumMismatch: 'Checksum verification failed. Please download again from the release page.',
        downloadRecommended: 'Recommended package',
        downloadAURHint: 'Arch detected: update via AUR',
        changelog: 'Changelog',
        noChangelog: 'No changelog available',
        later: 'Later',
        linuxUpdateHint: 'On Linux, Mindwtr cannot auto-install updates. After downloading, install via your package manager (e.g., yay -S mindwtr or paru -S mindwtr) or the downloaded package.',
        saved: 'Settings saved',
        selectSyncFolderTitle: 'Select sync folder',
        selectObsidianVaultTitle: 'Select Obsidian vault',
        system: 'System',
        light: 'Light',
        dark: 'Dark',
        eink: 'E-Ink',
        nord: 'Nord',
        sepia: 'Sepia',
        close: 'Close',
    },
    zh: {
        title: '设置',
        general: '通用',
        integrations: '集成',
        advanced: '高级',
        subtitle: '自定义您的 Mindwtr 体验',
        searchPlaceholder: '搜索设置…',
        back: '返回',
        features: '功能',
        featuresDesc: '按需开启可选信号。',
        lookAndFeel: '外观与风格',
        localization: '本地化',
        input: '输入',
        windowBehavior: '窗口行为',
        appearance: '外观',
        density: '密度',
        densityDesc: '调整列表间距以显示更多内容。',
        densityComfortable: '舒适',
        densityCompact: '紧凑',
        textSize: '文字大小',
        textSizeDesc: '调整桌面应用中的界面文字。',
        textSizeSmall: '小',
        textSizeDefault: '默认',
        textSizeLarge: '大',
        textSizeExtraLarge: '特大',
        showTaskAge: '显示任务年龄',
        showTaskAgeDesc: '在任务元数据中显示任务创建距今多久。',
        gtd: 'GTD',
        gtdDesc: 'Mindwtr 开箱即可使用。只有当你想调整 GTD 流程时，再改这些默认设置。',
        inboxProcessing: '收集箱处理',
        inboxProcessingDesc: '按你的习惯调整收集箱处理流程。',
        inboxDefaultMode: '默认模式',
        inboxModeGuided: '引导式',
        inboxModeQuick: '快速',
        inboxTwoMinuteEnabled: '显示“两分钟内完成”快捷选项',
        inboxTwoMinuteFirst: '先询问两分钟规则',
        inboxProjectFirst: '提前询问项目归属',
        inboxContextStepEnabled: '包含情境与标签步骤',
        inboxScheduleEnabled: '处理中允许安排日期',
        inboxReferenceEnabled: '处理中提供参考资料选项',
        captureDefault: '默认捕获方式',
        captureDefaultDesc: '选择快速捕获默认使用文本或语音。',
        captureDefaultText: '文本',
        captureDefaultAudio: '语音',
        captureSaveAudio: '保留语音附件',
        captureSaveAudioDesc: '转录后仍保留音频文件。',
        quickAddAutoClean: '整理快速添加文本',
        quickAddAutoCleanDesc: '应用后从标题中移除识别到的日期、标签和情境。关闭则完全保留你输入的文本。',
        markdownEditorAssist: '编辑器输入辅助',
        markdownEditorAssistDesc: '编辑描述时自动补全括号、续写列表、将粘贴的网址转为链接并提示引用。关闭后描述为纯文本，不再插入任何字符。',
        autoArchive: '自动归档完成任务',
        autoArchiveDesc: '在设定天数后将已完成任务移入归档。',
        autoArchiveNever: '从不（保留在已完成）',
        autoArchiveDayUnit: '天',
        defaultScheduleTime: '默认安排时间',
        defaultScheduleTimeDesc: '可选。选择日期后自动填入开始、截止和回顾时间。留空则保持仅日期。',
        defaultArea: '新任务默认领域',
        defaultAreaDesc: '适用于新任务，包括收集箱捕获。你仍可为单个任务更改或清除领域。',
        defaultAreaNone: '无领域',
        defaultAreaActive: '当前领域筛选',
        focusTaskLimit: '今日焦点上限',
        focusTaskLimitDesc: '每天可加星加入今日焦点的最大任务数。',
        defaultProjectFlowMode: '默认项目流程',
        defaultProjectFlowModeDesc: '仅在创建新项目时应用。现有项目保留当前流程。',
        projectFlowParallel: '并行',
        projectFlowSequential: '顺序',
        language: '语言',
        weekStart: '每周开始于',
        weekStartSunday: '周日',
        weekStartSystem: '跟随系统',
        weekStartMonday: '周一',
        weekStartSaturday: '周六',
        dateFormat: '日期格式',
        dateFormatSystem: '系统默认',
        dateFormatDmy: '日 / 月 / 年',
        dateFormatMdy: '月 / 日 / 年',
        dateFormatYmd: '年 / 月 / 日',
        calendarSystem: '日历系统',
        calendarSystemGregorian: '公历',
        calendarSystemJalali: '贾拉利历（太阳回历）',
        timeFormat: '时间格式',
        timeFormatSystem: '系统默认',
        timeFormat12h: '12 小时',
        timeFormat24h: '24 小时',
        keybindings: '快捷键',
        keybindingsDesc: '选择桌面端偏好的快捷键风格。',
        undoNotifications: '撤销通知',
        undoNotificationsDesc: '在将任务标记为已完成或删除后显示可撤销提示。',
        globalQuickAddShortcut: '全局快速添加快捷键',
        globalQuickAddShortcutDesc: '用于系统级快速收集，即使 Mindwtr 未聚焦也可触发。',
        globalQuickAddFlatpakDesc: 'Flatpak/Wayland 环境无法由 Mindwtr 直接注册这个快捷键。',
        globalQuickAddFlatpakCommand: 'Flatpak 自定义快捷键命令',
        globalQuickAddFlatpakCommandDesc: '请在桌面环境的快捷键设置中绑定这个命令。',
        keybindingStandard: '标准',
        keybindingVim: 'Vim',
        keybindingEmacs: 'Emacs',
        viewShortcuts: '查看快捷键',
        windowDecorations: '窗口装饰',
        windowDecorationsDesc: '显示系统标题栏和窗口边框。',
        closeBehavior: '关闭窗口行为',
        closeBehaviorDesc: '选择关闭窗口时的操作。',
        closeBehaviorAsk: '每次询问',
        closeBehaviorTray: '保留在托盘',
        closeBehaviorQuit: '退出应用',
        launchAtStartup: '开机自动启动',
        launchAtStartupDesc: '登录这台电脑时自动启动 Mindwtr。',
        showTray: '显示系统托盘图标',
        showTrayDesc: '在系统托盘中显示应用图标以便快速访问。',
        automation: '自动化',
        rendering: '渲染',
        softwareRendering: '使用软件渲染',
        softwareRenderingDesc: '需要重启。仅用于空白窗口、闪烁或显卡驱动问题。',
        network: '网络',
        localApiServer: '启用本地 API 服务器',
        localApiPort: '端口',
        localApiPortDesc: '仅限 localhost。默认：3456。',
        localApiToken: 'Bearer 令牌',
        localApiTokenDesc: '每个请求都必须在 Authorization 请求头中提供。',
        localApiSecurityNote: '拥有此令牌的本地应用和脚本可以读取并修改 Mindwtr 数据。',
        localApiStopped: '关闭',
        localApiUnavailable: '仅桌面应用可用',
        localApiPortInvalid: '请输入 1024 到 65535 之间的端口。',
        taskEditorLayout: '任务编辑布局',
        taskEditorLayoutDesc: '选择默认显示的任务编辑字段。',
        taskEditorLayoutHint: '隐藏字段仅在有内容或点击“更多选项”后显示。',
        taskEditorPresentation: '编辑器打开方式',
        taskEditorPresentationDesc: '选择在桌面端编辑任务时的打开方式。',
        taskEditorPresentationInline: '侧边预览',
        taskEditorPresentationInlineDesc: '在当前视图内打开编辑器，适合快速编辑。',
        taskEditorPresentationModal: '弹窗',
        taskEditorPresentationModalDesc: '在居中的弹窗中打开编辑器，适合专注编辑。',
        taskEditorLayoutReset: '重置布局',
        taskEditorSection: '分组',
        taskEditorDefaultOpen: '默认展开的分组',
        taskEditorOpenByDefault: '默认展开',
        taskEditorDefaultOpenDesc: '让这些任务编辑分组在没有现有内容时也默认展开。',
        taskEditorFieldStatus: '状态',
        taskEditorFieldProject: '项目',
        taskEditorFieldSection: '分组',
        taskEditorFieldArea: '领域',
        taskEditorFieldPriority: '优先级',
        taskEditorFieldEnergyLevel: '精力水平',
        taskEditorFieldAssignedTo: '负责人',
        taskEditorFieldContexts: '情境',
        taskEditorFieldDescription: '描述',
        taskEditorFieldLocation: '地点',
        taskEditorFieldTags: '标签',
        taskEditorFieldTimeEstimate: '时间预估',
        taskEditorFieldRecurrence: '重复',
        taskEditorFieldStartTime: '开始日期',
        taskEditorFieldDueDate: '截止日期',
        taskEditorFieldReviewAt: '回顾日期',
        taskEditorFieldAttachments: '附件',
        taskEditorFieldChecklist: '清单',
        taskEditorFieldTextDirection: '文本方向',
        featurePriorities: '优先级',
        featurePrioritiesDesc: '为任务显示优先级标记。',
        featureTimeEstimates: '时间估算',
        featureTimeEstimatesDesc: '为时间管理添加时长估计。',
        featurePomodoro: '番茄钟',
        featurePomodoroDesc: '在聚焦视图中启用可选的番茄钟面板。',
        pomodoroCustomPreset: '自定义预设',
        pomodoroCustomPresetDesc: '添加一个额外的专注/休息预设。若与内置预设相同，将继续只显示内置选项。',
        pomodoroFocusMinutes: '专注分钟',
        pomodoroBreakMinutes: '休息分钟',
        pomodoroLinkTask: '将计时器关联到任务',
        pomodoroLinkTaskDesc: '在聚焦中显示计时任务选择器和完成任务操作。',
        pomodoroAutoStartBreaks: '自动开始休息',
        pomodoroAutoStartBreaksDesc: '当专注阶段结束时，自动开始休息计时。',
        pomodoroAutoStartFocus: '自动开始专注',
        pomodoroAutoStartFocusDesc: '当休息阶段结束时，自动开始下一轮专注计时。',
        notifications: '通知',
        notificationsDesc: '启用任务提醒与每日简报通知。',
        notificationsEnable: '启用通知',
        startDateNotifications: '开始日期提醒',
        startDateNotificationsDesc: '在任务开始日期/时间到达时提醒我。',
        dueDateNotifications: '截止日期提醒',
        dueDateNotificationsDesc: '在任务截止日期/时间到达时提醒我。',
        reviewAtNotifications: '回顾日期提醒',
        reviewAtNotificationsDesc: '在回顾（tickler）日期到期时提醒我。',
        ai: 'AI 助手',
        aiDesc: '帮助澄清与拆解任务（可选）。',
        aiUsageTitle: 'AI 在哪里用、怎么用',
        aiUsageClarify: '澄清：打开任务，点击编辑器中的 ✨ 星标按钮，选择“澄清”，把含糊的任务改写为明确的下一步行动。',
        aiUsageBreakdown: '拆解：在同一个 ✨ 菜单中，选择“拆解”，把任务或项目拆分为具体步骤。',
        aiUsageSuggestions: '建议：输入任务标题或备注时，下方会出现关于情境、时间估算和标签的 ✨ 建议——点击即可应用。',
        aiUsageReview: '每周回顾：打开每周回顾，进入 AI 步骤，点击“运行”即可获得针对过期任务的建议行动。',
        aiEnable: '启用 AI 助手',
        aiProvider: '服务商',
        aiProviderOpenAI: 'OpenAI',
        aiProviderGemini: 'Gemini',
        aiProviderAnthropic: 'Anthropic（Claude）',
        aiModel: '模型',
        aiBaseUrl: '自定义 OpenAI 兼容基础 URL',
        aiBaseUrlHint: '官方 OpenAI 请留空。若使用本地或第三方 OpenAI 兼容接口，例如 llama.cpp、Ollama、LM Studio、GLM 或 vLLM，请在这里填写。',
        aiBaseUrlModelHint: '这个模型看起来不是官方 OpenAI 模型。如果你在使用 GLM 或其他 OpenAI 兼容服务，请设置自定义基础 URL。',
        aiExtraBodyParams: '额外请求参数',
        aiExtraBodyParamsDesc: '可选 JSON 对象，会合并到 OpenAI 兼容请求中。',
        aiExtraBodyParamsHint: 'model、messages、response_format 等核心字段会被保护。示例：{ "thinking": { "type": "disabled" } }',
        aiExtraBodyParamsInvalid: '请输入有效的 JSON 对象。',
        aiExtraBodyParamsSave: '保存参数',
        aiApiKey: 'API 密钥',
        aiApiKeyHint: '仅保存在本机，不会同步。官方 OpenAI 必须填写密钥。自定义 OpenAI 兼容端点也可能需要密钥；仅当该端点允许匿名访问时才可留空。',
        aiReasoning: '推理强度',
        aiReasoningHint: '仅用于 GPT-5 模型。',
        aiEffortLow: '低',
        aiEffortMedium: '中',
        aiEffortHigh: '高',
        aiCopilotModel: '助手模型',
        aiCopilotHint: '用于快速补全建议。',
        aiConsentTitle: '启用 AI 功能？',
        aiConsentDescription: '要使用此功能，您的任务数据将发送到 {provider} 进行处理。该数据受其隐私政策约束。Mindwtr 不会收集这些数据。是否继续？',
        aiConsentCancel: '取消',
        aiConsentAgree: '同意',
        aiThinkingBudget: '思考预算',
        aiThinkingHint: '仅用于 Claude/Gemini。0 代表关闭深度思考。',
        aiThinkingEnable: '启用思考',
        aiThinkingEnableDesc: '为复杂任务启用扩展推理。',
        aiThinkingOff: '关闭',
        aiThinkingLow: '低',
        aiThinkingMedium: '中',
        aiThinkingHigh: '高',
        speechTitle: '语音转文字',
        speechDesc: '转录语音并映射到任务字段。',
        speechEnable: '启用语音转文字',
        speechProvider: '语音服务商',
        speechProviderOffline: '本地（Whisper）',
        speechProviderParakeet: 'Parakeet v3 实验版',
        speechModel: '语音模型',
        speechOfflineModel: '离线模型',
        speechOfflineModelDesc: '下载一次即可离线转录。',
        speechParakeetModelDesc: '下载一次即可安装 Parakeet ASR 模型用于本地转录。Mindwtr 不内置模型权重。',
        speechParakeetModelPath: '安装文件夹',
        speechParakeetModelPathPlaceholder: 'App data folder',
        speechOfflineReady: '模型已下载',
        speechOfflineNotDownloaded: '尚未下载模型',
        speechOfflineEstimatedSize: '预计下载大小',
        speechOfflinePathSet: '模型路径已设置',
        speechOfflineDownload: '下载',
        speechOfflineDownloadSuccess: '下载完成',
        speechOfflineDelete: '删除',
        speechOfflineDownloadRuntime: '正在下载运行时',
        speechOfflineDownloadModel: '正在下载模型',
        speechOfflineInstalling: '正在安装',
        speechOfflineDownloadError: '离线模型下载失败',
        speechLanguage: '语音语言',
        speechLanguageHint: '可填写语言名称或代码，留空则自动检测。',
        speechLanguageAuto: '自动检测语言',
        speechMode: '处理模式',
        speechModeHint: '智能解析可提取日期与字段，纯转录仅输出文本。',
        speechModeSmart: '智能解析',
        speechModeTranscript: '仅转录',
        speechFieldStrategy: '字段映射',
        speechFieldStrategyHint: '选择默认写入标题或描述的位置。',
        speechFieldSmart: '智能',
        speechFieldTitle: '标题',
        speechFieldDescription: '描述',
        dailyDigest: '每日简报',
        dailyDigestDesc: '早间简报与晚间回顾提醒。',
        dailyDigestMorning: '早间简报',
        dailyDigestEvening: '晚间回顾',
        weeklyReview: '每周回顾',
        weeklyReviewDesc: '在你设定的时间提醒进行每周回顾。',
        weeklyReviewDay: '回顾日期',
        weeklyReviewTime: '回顾时间',
        weeklyReviewConfig: '每周回顾流程',
        weeklyReviewConfigDesc: '配置每周回顾中显示哪些步骤。',
        weeklyReviewIncludeContextsStep: '包含情境步骤',
        weeklyReviewIncludeContextsStepDesc: '在“等待中”和“项目”之间显示专门的情境回顾步骤。',
        on: '开启',
        off: '关闭',
        visible: '显示',
        hidden: '隐藏',
        manage: '管理',
        dataTransfer: '数据传输',
        dataTransferDesc: '导出完整备份、从备份恢复本地数据，或导入 Todoist、DGT GTD 与 OmniFocus 导出文件。',
        exportBackup: '导出备份',
        exportBackupDesc: '将当前本地数据保存为 JSON 备份文件。',
        restoreBackup: '恢复备份',
        restoreBackupDesc: '从 Mindwtr 备份 JSON 文件替换本地数据。',
        importTodoist: '从 Todoist 导入',
        importTodoistDesc: '将 Todoist 的 CSV 或 ZIP 导出导入为 Mindwtr 项目。',
        importTickTick: '从 TickTick 导入',
        importTickTickDesc: '将 TickTick 的 CSV 或 ZIP 备份导入为 Mindwtr 的领域、项目和任务。',
        importDgt: '从 DGT GTD 导入',
        importDgtDesc: '将 DGT GTD 的 JSON 或 ZIP 导出导入为 Mindwtr 的领域、项目和任务。',
        importOmniFocus: '从 OmniFocus 导入',
        importOmniFocusDesc: '将 OmniFocus 的 CSV、JSON 或 ZIP 导出导入为 Mindwtr 项目和收集箱任务。',
        diagnostics: '诊断',
        diagnosticsDesc: '帮助排查问题。',
        analyticsHeartbeat: '退出诊断',
        analyticsHeartbeatDesc: '诊断信息是匿名的，可帮助改进 Mindwtr。不包含任务内容、笔记或个人数据。打开此项即可停止发送。',
        analyticsHeartbeatDisableTitle: '退出诊断？',
        analyticsHeartbeatDisableDesc: '打开此项会停止发送匿名诊断信息。不发送任务内容、笔记或个人数据。',
        analyticsHeartbeatDisableConfirm: '退出',
        analyticsHeartbeatKeepEnabled: '继续发送',
        debugLogging: '调试日志',
        debugLoggingDesc: '将错误记录到本地以便提交反馈。',
        logFile: '日志文件',
        clearLog: '清除日志',
        sync: '同步',
        syncDescription:
            '选择 Mindwtr 的同步方式。支持的构建可一键连接 Dropbox；文件同步适合本地同步文件夹；WebDAV 和自托管适合自定义存储。',
        syncBackend: '同步后端',
        syncBackendOff: '关闭',
        syncBackendFile: '文件',
        syncBackendWebdav: 'WebDAV',
        syncBackendCloud: '自托管',
        syncBackendCloudkit: 'iCloud',
        syncBackendChoiceHint: '请选择一种同步方式。关闭同步会让数据只保留在本设备。',
        syncBackendGroupCloud: '云同步',
        syncBackendGroupCloudDesc: '由 Mindwtr 处理的简单账号同步。',
        syncBackendGroupFile: '文件夹 / 文件同步',
        syncBackendGroupFileDesc: '使用您自己的本地同步文件夹。',
        syncBackendGroupAdvanced: '高级 / 自定义服务器',
        syncBackendGroupAdvancedDesc: '使用 WebDAV 或您自己的 Mindwtr Cloud 端点。',
        networkProxyUrl: '代理地址',
        networkProxyUrlDesc: '可选的桌面 HTTP(S) 代理，用于同步和外部日历请求。',
        networkProxyUrlHint: '使用 http://host:port 或 https://host:port。凭据可包含在地址中。此设置不会在设备间同步。',
        networkProxyInvalid: '请输入有效的 http(s) 代理地址。',
        networkProxySave: '保存代理',
        syncPreferences: '设置同步选项',
        syncPreferencesDesc: '选择要在设备间同步的偏好设置。',
        syncPreferenceAppearance: '外观（主题、密度、文字大小、任务年龄）',
        syncPreferenceLanguage: '语言与日期格式',
        syncPreferenceGtd: '日程默认值',
        syncPreferenceSavedFilters: '已保存筛选',
        syncPreferenceExternalCalendars: '外部日历 URL',
        syncPreferenceAi: 'AI 设置（模型、提供商）',
        syncPreferenceAiHint: 'API 密钥和本地模型路径不会同步。',
        backgroundSync: '后台同步',
        backgroundSyncDesc: '桌面端会在启动时、应用重新获得焦点时、Mindwtr 运行时每 15 分钟一次，以及任务/项目变更后短暂延迟同步。关闭到托盘可保持运行；开机自动启动可在登录后启动。退出应用会停止桌面后台同步。',
        attachmentsCleanup: '附件清理',
        attachmentsCleanupDesc: '从设备和同步存储中删除已删除或孤立的附件文件。',
        attachmentsCleanupLastRun: '上次清理',
        attachmentsCleanupNever: '从未',
        attachmentsCleanupPendingDeletes: '待处理远程删除',
        attachmentsCleanupPendingDeletesClear: '清除待处理删除',
        attachmentsCleanupPendingDeletesConfirm: '仅当你不再希望 Mindwtr 从旧同步后端删除这些文件时才清除。此操作不会删除任何文件。',
        attachmentsCleanupPendingDeletesConfirmTitle: '清除待处理的附件删除？',
        attachmentsCleanupRun: '立即清理',
        attachmentsCleanupRunning: '清理中...',
        calendar: '日历',
        calendarDesc: '通过 ICS 订阅地址或本地 .ics 文件查看外部日历（只读）。',
        externalCalendars: '外部日历',
        calendarName: '名称',
        calendarUrl: 'ICS 地址',
        calendarAdd: '添加日历',
        calendarChooseLocalFile: '选择本地 .ics 文件',
        calendarRemove: '移除',
        calendarSystemTitle: 'Apple 日历（macOS）',
        calendarSystemDesc: '通过 EventKit 读取 macOS 已同步的 Apple 日历账户（iCloud、Google、Exchange）事件。',
        calendarSystemStatus: 'Apple 日历访问',
        calendarSystemPermissionGranted: '已授权',
        calendarSystemPermissionUndetermined: '未请求',
        calendarSystemPermissionDenied: '已拒绝',
        calendarSystemPermissionUnsupported: '不支持',
        calendarSystemRequestAccess: '请求访问',
        calendarSystemDeniedHint: '日历访问被拒绝。请在 macOS 系统设置 > 隐私与安全性 > 日历 中为 Mindwtr 开启权限。',
        calendarPushTitle: '推送任务到 Apple 日历',
        calendarPushDesc: '将已安排的任务和带截止日期的任务写入选定的 Apple 日历。仅单向推送。',
        calendarPushEnable: '启用 Apple 日历推送',
        calendarPushTarget: '同步目标',
        calendarPushManagedTarget: 'Mindwtr 日历（自动创建）',
        calendarPushRefresh: '刷新日历',
        calendarPushLoading: '加载中...',
        calendarPushTargetHint: '使用专用 Mindwtr 日历可避免在共享日历中添加标题前缀。',
        syncFolderLocation: '同步文件夹',
        savePath: '保存',
        browse: '浏览…',
        syncNow: '立即同步',
        syncing: '同步中…',
        syncQueued: '同步已排队',
        pathHint: '请选择文件夹（如 ~/Sync/mindwtr）。使用 Syncthing 时建议开启 Send & Receive 与 Watch for Changes，并在切换设备前手动点“立即同步”。',
        webdavUrl: 'WebDAV 地址',
        webdavUsername: '用户名',
        webdavPassword: '密码',
        webdavSave: '保存 WebDAV',
        testConnection: '测试连接',
        webdavTestHint: '仅验证地址和凭据，不执行数据同步',
        webdavTestAccessibility: '测试 WebDAV 连接',
        webdavHint: '请输入同步文件夹地址，Mindwtr 会在其中存放 data.json（例如 https://example.com/remote.php/dav/files/user/mindwtr）。',
        allowInsecureHttp: '允许不安全连接（HTTP）',
        allowInsecureHttpHint: '仅允许本机或私有网络 HTTP。数据将以未加密方式传输。',
        cloudUrl: '自托管地址',
        cloudToken: '访问令牌',
        cloudRememberToken: '在此浏览器中记住令牌',
        cloudRememberTokenHint: '将令牌保存在 localStorage 中，使 PWA 重新打开后仍可同步。请勿在共享设备上使用。',
        cloudSave: '保存自托管配置',
        cloudHint: '请输入自托管基础地址（例如 https://example.com 或 https://example.com/mindwtr），Mindwtr 会自动追加 /v1/data。',
        cloudProvider: '云服务提供方',
        cloudProviderSelfHosted: '自托管',
        cloudProviderDropbox: 'Dropbox',
        cloudProviderCloudkit: 'iCloud',
        cloudkitDesc: '通过 iCloud 在 Apple 设备间同步您的任务、项目和领域。无需额外设置。',
        dropboxAppKey: 'Dropbox 账号',
        dropboxAppKeyHint: 'Dropbox App Key 在构建/发布时注入。',
        dropboxRedirectUri: '回调地址',
        dropboxStatus: '状态',
        dropboxConnected: '已连接',
        dropboxNotConnected: '未连接',
        dropboxConnect: '连接 Dropbox',
        dropboxDisconnect: '断开 Dropbox',
        dropboxTest: '测试连接',
        dropboxTestReachable: '可访问',
        dropboxTestFailed: '失败',
        obsidianVault: 'Obsidian 资料库导入',
        obsidianVaultDesc: '从本地 Obsidian 资料库导入任务。Obsidian 保留笔记与捕获来源，Mindwtr 管理原生承诺事项。',
        obsidianEnable: '启用 Obsidian 集成',
        obsidianVaultPath: '资料库文件夹',
        obsidianVaultPathHint: '选择资料库根目录。Mindwtr 会从配置的扫描文件夹读取 Markdown 笔记。',
        obsidianDetectedVaults: '检测到的资料库：',
        obsidianScanFolders: '扫描文件夹',
        obsidianScanFoldersHint: '每行填写一个相对文件夹。使用 / 扫描整个资料库。',
        obsidianInboxFile: 'Mindwtr 收件箱笔记',
        obsidianInboxFileHint: '用于从 Mindwtr 创建任务的相对 Markdown 路径。缺失的父目录会在需要时自动创建。',
        obsidianDataview: 'Dataview 元数据',
        obsidianDataviewDesc: '用于已经使用 Dataview 内联字段的资料库的可选兼容设置。',
        obsidianDataviewMetadata: '导入 Dataview 字段',
        obsidianDataviewMetadataHint: '读取 project::、context::、due::、scheduled::、priority:: 和 estimate:: 字段。Mindwtr 不会回写这些字段。',
        obsidianTaskNotes: 'TaskNotes',
        obsidianTaskNotesDesc: '自动检测 TaskNotes 文件。这里仅控制是否包含归档任务，以及 Mindwtr 创建新任务时使用的格式。',
        obsidianTaskNotesIncludeArchived: '包含已归档的 TaskNotes',
        obsidianTaskNotesIncludeArchivedHint: '关闭后，已归档的 TaskNotes 文件不会出现在导入任务列表中。',
        obsidianNewTaskFormat: '新任务格式',
        obsidianNewTaskFormatHint: '自动模式会跟随当前资料库检测到的格式。仅在你希望 Mindwtr 创建的任务使用不同格式时再覆盖。',
        obsidianNewTaskFormatAuto: '自动检测',
        obsidianNewTaskFormatInline: '内联复选框',
        obsidianNewTaskFormatTaskNotes: 'TaskNotes 笔记',
        obsidianWatching: '正在监听资料库变更。',
        obsidianWatcherUnavailable: '实时更新不可用。',
        obsidianSave: '保存 Obsidian 设置',
        obsidianRemove: '断开资料库',
        obsidianRescan: '重新扫描资料库',
        obsidianRescanning: '正在扫描资料库...',
        obsidianLastScanned: '上次 Obsidian 扫描',
        obsidianNeverScanned: '从未扫描',
        obsidianMissingMarker: '该文件夹不包含 .obsidian 目录。如果你的资料库布局比较特殊，仍然可以保存。',
        obsidianChooseVaultFailed: '选择 Obsidian 资料库文件夹失败。',
        obsidianSaveFailed: '保存 Obsidian 配置失败。',
        obsidianRemoveFailed: '移除 Obsidian 配置失败。',
        obsidianScanFailed: '扫描 Obsidian 资料库失败。',
        obsidianScanSuccess: 'Obsidian 资料库扫描完成。',
        lastSync: '上次同步',
        lastSyncNever: '从未同步',
        lastSyncSuccess: '同步完成',
        lastSyncError: '同步失败',
        lastSyncConflict: '已解决冲突',
        lastSyncConflicts: '冲突',
        lastSyncSkew: '时钟偏差',
        lastSyncAdjusted: '时间修正',
        lastSyncConflictIds: '冲突 ID',
        syncConflictKeptThisDevice: '保留了本设备的版本',
        syncConflictKeptOtherDevice: '保留了同步的版本',
        syncConflictChanged: '变更：{{fields}}',
        syncConflictDeleteRestore: '删除与编辑冲突',
        syncConflictMore: '还有 {{count}} 个已解决的冲突',
        syncHistory: '同步历史',
        recoverySnapshots: '恢复快照',
        recoverySnapshotsDesc: '同步前创建。最多保留 7 天（最多 5 个文件）。',
        recoverySnapshotsLoading: '正在加载快照…',
        recoverySnapshotsEmpty: '暂无快照。',
        recoverySnapshotsRestore: '恢复',
        recoverySnapshotsConfirm: '恢复快照 {snapshot}？这将替换当前本地数据。',
        recoverySnapshotsConfirmTitle: '恢复快照？',
        recoverySnapshotsConfirmCancel: '取消',
        about: '关于',
        version: '版本',
        installChannel: '安装渠道',
        developer: '开发者',
        website: '开发者网站',
        github: 'GitHub',
        documentation: '文档',
        sponsorProject: '支持开发',
        license: '许可证',
        feedback: '发送反馈',
        feedbackDesc: '提交错误报告或功能请求。无需账号。',
        feedbackCategory: '类别',
        feedbackCategoryBug: '错误报告',
        feedbackCategoryFeature: '功能请求',
        feedbackCategoryOther: '其他',
        feedbackMessage: '内容',
        feedbackMessagePlaceholder: '告诉我们发生了什么，或什么改进会有帮助。',
        feedbackMessagePlaceholderBug: '你期望发生什么？实际发生了什么？如果可以，请写出复现步骤。',
        feedbackMessagePlaceholderFeature: '你想完成什么？现在卡在哪里？什么改进会有帮助？',
        feedbackMessagePlaceholderOther: '告诉我们你的想法。',
        feedbackWhere: '发生在哪里？',
        feedbackWherePlaceholder: '选择页面或流程（可选）',
        feedbackWhereMessagePrefix: '位置',
        feedbackWhereInbox: '收集箱',
        feedbackWhereFocus: '专注',
        feedbackWhereProjects: '项目',
        feedbackWhereReview: '回顾',
        feedbackWhereSettings: '设置',
        feedbackWhereSync: '同步',
        feedbackWhereImportExport: '导入或导出',
        feedbackWhereNotifications: '通知',
        feedbackWhereOther: '其他',
        feedbackEmail: '回复邮箱（可选）',
        feedbackEmailPlaceholder: 'name@example.com',
        feedbackIncludeDiagnostics: '包含最近诊断信息',
        feedbackIncludeDiagnosticsDesc: '附加最近的已清理应用日志。不会附加任务数据、备份或截图。',
        feedbackPrivacy: '这会发送你的反馈内容、应用版本、平台，以及你选择包含的诊断信息。只有你填写回复邮箱时才会发送邮箱。不会附加任务内容。',
        feedbackSubmit: '发送反馈',
        feedbackSending: '发送中...',
        feedbackSent: '反馈已发送，谢谢。',
        feedbackFailed: '反馈发送失败。内容仍会保留，请稍后重试。',
        feedbackUnavailable: '此版本未配置反馈通道。',
        feedbackUnavailableDesc: '你仍可通过 GitHub issue 模板提交错误报告或功能请求。',
        feedbackOpenGitHubIssue: '打开 GitHub issue',
        feedbackRequired: '请先填写简短内容。',
        feedbackInvalidEmail: '请输入有效邮箱，或留空。',
        checkForUpdates: '检查更新',
        checkStoreUpdates: '检查 Microsoft Store 更新',
        checking: '检查中…',
        upToDate: '您正在使用最新版本！',
        updateAvailable: '有可用更新',
        checkFailed: '检查更新失败',
        storeUpdateHint: '更新由 Microsoft Store 管理。',
        download: '下载',
        downloadStarting: '正在打开下载…',
        downloadStarted: '已在浏览器开始下载。',
        downloadFailed: '打开下载链接失败。',
        downloadChecksumMismatch: '校验和验证失败，请从发布页面重新下载。',
        downloadRecommended: '推荐下载包',
        downloadAURHint: '检测到 Arch：建议使用 AUR 更新',
        changelog: '更新日志',
        noChangelog: '暂无更新日志',
        later: '稍后',
        linuxUpdateHint: 'Linux 上无法自动安装更新。下载后请使用包管理器更新（如 yay -S mindwtr 或 paru -S mindwtr），或安装下载的包。',
        saved: '设置已保存',
        selectSyncFolderTitle: '选择同步文件夹',
        selectObsidianVaultTitle: '选择 Obsidian 资料库',
        system: '系统',
        light: '浅色',
        dark: '深色',
        eink: '电子墨水',
        nord: 'Nord',
        sepia: '复古米黄',
        close: '关闭',
    },
} as const;

export type SettingsLabels = Record<keyof typeof labelFallback.en, string>;

export const zhHantLabelOverrides: Partial<SettingsLabels> = {
    searchPlaceholder: '搜索設置…',
    lookAndFeel: '外觀與風格',
    input: '輸入',
    windowBehavior: '窗口行為',
    textSizeDesc: '調整桌面應用的介面文字。',
    showTaskAge: '顯示任務年齡',
    showTaskAgeDesc: '在任務元數據中顯示任務創建距今多久。',
    defaultScheduleTime: '默認安排時間',
    defaultScheduleTimeDesc: '可選。選擇日期後自動填入開始、截止和回顧時間。留空則保持僅日期。',
    defaultArea: '新任務默認領域',
    defaultAreaDesc: '適用於新任務，包括收集箱捕獲。你仍可為單個任務更改或清除領域。',
    defaultAreaNone: '無領域',
    defaultAreaActive: '目前領域篩選',
    defaultProjectFlowMode: '默認項目流程',
    defaultProjectFlowModeDesc: '僅在創建新項目時應用。現有項目保留當前流程。',
    projectFlowParallel: '並行',
    projectFlowSequential: '順序',
    undoNotifications: '撤銷通知',
    undoNotificationsDesc: '在將任務標記為已完成或刪除後顯示可撤銷提示。',
    launchAtStartup: '開機自動啟動',
    launchAtStartupDesc: '登錄這台電腦時自動啟動 Mindwtr。',
    localApiServer: '啟用本地 API 伺服器',
    localApiPortDesc: '僅限 localhost。默認：3456。',
    localApiStopped: '關閉',
    taskEditorPresentation: '編輯器打開方式',
    taskEditorPresentationDesc: '選擇在桌面端編輯任務時的打開方式。',
    taskEditorPresentationInline: '側邊預覽',
    taskEditorPresentationInlineDesc: '在當前視圖內打開編輯器，適合快速編輯。',
    taskEditorPresentationModal: '彈窗',
    taskEditorPresentationModalDesc: '在居中的彈窗中打開編輯器，適合專注編輯。',
    dataTransfer: '數據傳輸',
    dataTransferDesc: '導出完整備份、從備份恢復本地數據，或導入 Todoist、DGT GTD 與 OmniFocus 導出文件。',
    exportBackupDesc: '將當前本地數據保存為 JSON 備份文件。',
    restoreBackup: '恢復備份',
    restoreBackupDesc: '從 Mindwtr 備份 JSON 文件替換本地數據。',
    importTodoist: '從 Todoist 導入',
    importTodoistDesc: '將 Todoist 的 CSV 或 ZIP 導出導入為 Mindwtr 項目。',
    importTickTick: '從 TickTick 導入',
    importTickTickDesc: '將 TickTick 的 CSV 或 ZIP 備份導入為 Mindwtr 的領域、項目和任務。',
    importDgt: '從 DGT GTD 導入',
    importDgtDesc: '將 DGT GTD 的 JSON 或 ZIP 導出導入為 Mindwtr 的領域、項目和任務。',
    importOmniFocus: '從 OmniFocus 導入',
    importOmniFocusDesc: '將 OmniFocus 的 CSV、JSON 或 ZIP 導出導入為 Mindwtr 項目和收集箱任務。',
    backgroundSync: '後台同步',
    backgroundSyncDesc: '桌面端會在啟動時、應用重新獲得焦點時、Mindwtr 運行時每 15 分鐘一次，以及任務/項目變更後短暫延遲同步。關閉到托盤可保持運行；開機自動啟動可在登錄後啟動。退出應用會停止桌面後台同步。',
    cloudRememberToken: '在此瀏覽器中記住令牌',
    cloudRememberTokenHint: '將令牌保存在 localStorage 中，使 PWA 重新打開後仍可同步。請勿在共享設備上使用。',
    attachmentsCleanupPendingDeletes: '待處理遠程刪除',
    attachmentsCleanupPendingDeletesClear: '清除待處理刪除',
    calendarChooseLocalFile: '選擇本地 .ics 文件',
    obsidianVault: 'Obsidian 資料庫導入',
    obsidianVaultDesc: '從本地 Obsidian 資料庫導入任務。Obsidian 保留筆記與捕獲來源，Mindwtr 管理原生承諾事項。',
    feedbackMessagePlaceholderBug: '你期望發生什麼？實際發生了什麼？如果可以，請寫出重現步驟。',
    feedbackMessagePlaceholderFeature: '你想完成什麼？現在卡在哪裡？什麼改進會有幫助？',
    feedbackMessagePlaceholderOther: '告訴我們你的想法。',
    feedbackWhere: '發生在哪裡？',
    feedbackWherePlaceholder: '選擇頁面或流程（可選）',
    feedbackWhereMessagePrefix: '位置',
    feedbackWhereInbox: '收集箱',
    feedbackWhereFocus: '專注',
    feedbackWhereProjects: '項目',
    feedbackWhereReview: '回顧',
    feedbackWhereSettings: '設置',
    feedbackWhereSync: '同步',
    feedbackWhereImportExport: '導入或導出',
    feedbackWhereNotifications: '通知',
    feedbackWhereOther: '其他',
    feedbackUnavailableDesc: '你仍可透過 GitHub issue 模板提交錯誤報告或功能請求。',
    feedbackOpenGitHubIssue: '打開 GitHub issue',
    sponsorProject: '支持開發',
};

export const getSettingsLabelFallback = (language: string): SettingsLabels => {
    if (language === 'zh-Hant') {
        return {
            ...labelFallback.zh,
            ...zhHantLabelOverrides,
        };
    }
    if (language === 'zh') {
        return labelFallback.zh;
    }
    return labelFallback.en;
};

export const labelKeyOverrides: Partial<Record<keyof SettingsLabels, string>> = {
    back: 'common.back',
    close: 'common.close',
    inboxModeGuided: 'process.modeGuided',
    inboxModeQuick: 'process.modeQuick',
    keybindings: 'keybindings.helpTitle',
    keybindingsDesc: 'settings.keybindingsDesc',
    keybindingStandard: 'keybindings.style.standard',
    keybindingVim: 'keybindings.style.vim',
    keybindingEmacs: 'keybindings.style.emacs',
    viewShortcuts: 'keybindings.openHelp',
    dateFormat: 'settings.dateFormat',
    dateFormatSystem: 'settings.dateFormatSystem',
    dateFormatDmy: 'settings.dateFormatDmy',
    dateFormatMdy: 'settings.dateFormatMdy',
    dateFormatYmd: 'settings.dateFormatYmd',
    calendarSystem: 'settings.calendarSystem',
    calendarSystemGregorian: 'settings.calendarSystemGregorian',
    calendarSystemJalali: 'settings.calendarSystemJalali',
    timeFormat: 'settings.timeFormat',
    timeFormatSystem: 'settings.timeFormatSystem',
    timeFormat12h: 'settings.timeFormat12h',
    timeFormat24h: 'settings.timeFormat24h',
    taskEditorLayoutReset: 'settings.resetToDefault',
    autoArchiveDayUnit: 'common.days',
    taskEditorFieldStatus: 'taskEdit.statusLabel',
    taskEditorFieldProject: 'taskEdit.projectLabel',
    taskEditorFieldSection: 'taskEdit.sectionLabel',
    taskEditorFieldArea: 'taskEdit.areaLabel',
    taskEditorFieldPriority: 'taskEdit.priorityLabel',
    taskEditorFieldEnergyLevel: 'taskEdit.energyLevel',
    taskEditorFieldAssignedTo: 'taskEdit.assignedTo',
    taskEditorFieldContexts: 'taskEdit.contextsLabel',
    taskEditorFieldDescription: 'taskEdit.descriptionLabel',
    taskEditorFieldLocation: 'taskEdit.locationLabel',
    taskEditorFieldTags: 'taskEdit.tagsLabel',
    taskEditorFieldTimeEstimate: 'taskEdit.timeEstimateLabel',
    taskEditorFieldRecurrence: 'taskEdit.recurrenceLabel',
    taskEditorFieldStartTime: 'taskEdit.startDateLabel',
    taskEditorFieldDueDate: 'taskEdit.dueDateLabel',
    taskEditorFieldReviewAt: 'taskEdit.reviewDateLabel',
    taskEditorFieldAttachments: 'attachments.title',
    taskEditorFieldChecklist: 'taskEdit.checklist',
    taskEditorFieldTextDirection: 'taskEdit.textDirectionLabel',
} as const;
