import { StyleSheet } from 'react-native';

export const projectsScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    inputContainer: {
        padding: 16,
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e5e5',
    },
    addProjectRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    filterSection: {
        gap: 8,
    },
    filterHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    filterToggleText: {
        fontSize: 12,
        fontWeight: '600',
        flexShrink: 0,
        minWidth: 48,
        textAlign: 'right',
    },
    tagFilterLabel: {
        fontSize: 12,
        fontWeight: '600',
        flex: 1,
        minWidth: 0,
    },
    tagFilterChips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    tagFilterChip: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: 1,
    },
    tagFilterText: {
        fontSize: 12,
        fontWeight: '600',
    },
    input: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 16,
    },
    addProjectInput: {
        flex: 1,
        minWidth: 0,
    },
    colorPicker: {
        flexDirection: 'row',
        gap: 8,
    },
    colorOption: {
        width: 32,
        height: 32,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    colorOptionSelected: {
        borderColor: '#000',
    },
    addIconButton: {
        width: 46,
        height: 46,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addButtonDisabled: {
        opacity: 0.5,
    },
    projectItem: {
        flexDirection: 'row',
        backgroundColor: '#f9f9f9',
        borderRadius: 8,
        padding: 12,
        marginBottom: 8,
        alignItems: 'center',
    },
    projectTouchArea: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    projectDetailScroll: {
        flexGrow: 1,
        paddingBottom: 24,
    },
    projectDetailRoot: {
        flex: 1,
    },
    projectTaskPinnedToolbar: {
        minHeight: 56,
        borderBottomWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    projectTaskPinnedControl: {
        width: 44,
        height: 44,
        borderRadius: 12,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    projectTaskPinnedControlIcon: {
        position: 'relative',
        alignItems: 'center',
        justifyContent: 'center',
    },
    projectTaskPinnedSpacer: {
        flex: 1,
    },
    projectTaskPinnedAddButton: {
        width: 56,
        height: 44,
        borderRadius: 14,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    projectTaskPinnedBadge: {
        minWidth: 18,
        height: 18,
        borderRadius: 9,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 4,
        position: 'absolute',
        right: -10,
        top: -8,
    },
    projectTaskPinnedBadgeText: {
        fontSize: 10,
        fontWeight: '800',
    },
    projectContent: {
        flex: 1,
    },
    sectionBlock: {
        marginBottom: 12,
    },
    collapsibleSectionToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 14,
        paddingBottom: 10,
        marginTop: 6,
    },
    collapsibleSectionToggleText: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.4,
        textTransform: 'uppercase',
    },
    collapsibleAreaHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 4,
        paddingBottom: 8,
    },
    collapsibleAreaHeaderContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flex: 1,
        paddingRight: 8,
    },
    collapsibleAreaDot: {
        width: 8,
        height: 8,
        borderRadius: 999,
        borderWidth: 1,
    },
    collapsibleAreaIcon: {
        fontSize: 10,
    },
    collapsibleAreaHeaderText: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.4,
        textTransform: 'uppercase',
        flexShrink: 1,
    },
    projectTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
        marginBottom: 4,
    },
    projectTitleContent: {
        flex: 1,
        minWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    projectTagDots: {
        flexDirection: 'row',
        gap: 4,
    },
    projectTagDot: {
        width: 6,
        height: 6,
        borderRadius: 999,
        opacity: 0.7,
    },
    projectTitle: {
        flexShrink: 1,
        fontSize: 16,
        fontWeight: '500',
    },
    projectTaskCountBadge: {
        minWidth: 22,
        minHeight: 20,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 999,
        borderWidth: 1,
        paddingHorizontal: 6,
    },
    projectTaskCountText: {
        fontSize: 11,
        fontWeight: '700',
        lineHeight: 14,
    },
    projectMeta: {
        fontSize: 12,
        color: '#666',
    },
    projectSwipeAction: {
        width: 96,
        marginBottom: 8,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
    },
    projectSwipeDuplicateAction: {
        backgroundColor: '#3B82F6',
    },
    projectSwipeDeleteAction: {
        backgroundColor: '#EF4444',
    },
    projectSwipeActionText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '700',
    },
    emptyContainer: {
        padding: 48,
        alignItems: 'center',
    },
    emptyText: {
        color: '#999',
        fontSize: 16,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e5e5',
    },
    backButton: {
        padding: 8,
        width: 60,
    },
    backButtonText: {
        fontSize: 16,
        color: '#007AFF',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    sequentialBadge: {
        backgroundColor: '#DBEAFE',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    sequentialBadgeText: {
        fontSize: 10,
        color: '#1D4ED8',
        fontWeight: '500',
    },
    sequentialToggle: {
        minHeight: 30,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        borderWidth: 1,
        backgroundColor: '#F3F4F6',
    },
    projectTypeControls: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    projectTypeHelpButton: {
        width: 30,
        height: 30,
        borderRadius: 8,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sequentialToggleText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },
    sequentialScopeOptions: {
        flexDirection: 'row',
        gap: 8,
        marginTop: 8,
    },
    sequentialScopeButton: {
        flex: 1,
        minHeight: 36,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        borderWidth: 1,
        paddingHorizontal: 8,
        paddingVertical: 8,
    },
    sequentialScopeText: {
        fontSize: 12,
        fontWeight: '700',
        textAlign: 'center',
    },
    statusPicker: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        borderWidth: 1,
    },
    statusPickerText: {
        fontSize: 12,
        fontWeight: '600',
    },
    statusMenu: {
        marginHorizontal: 16,
        marginBottom: 10,
        borderWidth: 1,
        borderRadius: 8,
        overflow: 'hidden',
    },
    statusMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    statusMenuText: {
        fontSize: 12,
        fontWeight: '600',
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 999,
    },
    statusButtonText: {
        fontSize: 12,
        fontWeight: '600',
    },
    completeButton: {
        backgroundColor: '#10B98120',
    },
    archiveButton: {
        backgroundColor: '#6B728020',
    },
    reactivateButton: {
        backgroundColor: '#3B82F620',
    },
    completeText: {
        color: '#10B981',
    },
    archiveText: {
        color: '#6B7280',
    },
    reactivateText: {
        color: '#3B82F6',
    },
    notesContainer: {
        borderBottomWidth: 1,
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    notesHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    detailsToggle: {
        borderRadius: 10,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginTop: 6,
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    detailsToggleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        minHeight: 30,
    },
    detailsToggleText: {
        fontSize: 14,
        fontWeight: '600',
    },
    notesHeader: {
        paddingVertical: 8,
    },
    notesTitle: {
        fontSize: 14,
        fontWeight: '600',
    },
    notesInput: {
        marginTop: 8,
        borderRadius: 8,
        padding: 10,
        minHeight: 100,
        textAlignVertical: 'top',
        fontSize: 14,
        borderWidth: 1,
    },
    smallButton: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        borderWidth: 1,
    },
    smallButtonText: {
        fontSize: 12,
        fontWeight: '700',
    },
    markdownPreview: {
        marginTop: 8,
        padding: 12,
        borderRadius: 10,
        borderWidth: 1,
    },
    attachmentsContainer: {
        borderBottomWidth: 1,
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    attachmentsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    attachmentsTitle: {
        fontSize: 14,
        fontWeight: '700',
    },
    attachmentsActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    helperText: {
        marginTop: 8,
        fontSize: 13,
    },
    projectSectionPillRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 10,
    },
    projectSectionPill: {
        maxWidth: '100%',
        borderRadius: 999,
        borderWidth: 1,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    projectSectionPillText: {
        fontSize: 12,
        fontWeight: '700',
    },
    attachmentsList: {
        marginTop: 10,
        borderWidth: 1,
        borderRadius: 10,
        overflow: 'hidden',
    },
    attachmentRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderBottomWidth: 1,
    },
    attachmentTitleWrap: {
        flex: 1,
        paddingRight: 10,
    },
    attachmentTitle: {
        fontSize: 13,
        fontWeight: '600',
    },
    attachmentDownload: {
        fontSize: 12,
        fontWeight: '600',
        marginRight: 10,
    },
    attachmentStatus: {
        fontSize: 12,
        fontWeight: '500',
        marginRight: 10,
    },
    attachmentRemove: {
        fontSize: 12,
        fontWeight: '700',
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.45)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    linkModalCard: {
        width: '100%',
        maxWidth: 420,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
    },
    linkModalTitle: {
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 12,
    },
    linkModalInput: {
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
    },
    linkModalHint: {
        fontSize: 12,
        marginTop: 8,
    },
    linkModalButtons: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
        marginTop: 14,
    },
    previewCard: {
        width: '100%',
        maxWidth: 520,
        borderRadius: 12,
        borderWidth: 1,
        overflow: 'hidden',
    },
    previewHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderBottomWidth: StyleSheet.hairlineWidth,
    },
    previewTitle: {
        flex: 1,
        fontSize: 14,
        fontWeight: '700',
    },
    previewImage: {
        width: '100%',
        height: 360,
        backgroundColor: '#000',
    },
    sectionManagerCard: {
        width: '100%',
        maxWidth: 420,
        maxHeight: '82%',
        borderRadius: 12,
        borderWidth: 1,
        padding: 16,
        gap: 12,
    },
    sectionManagerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    sectionManagerTitle: {
        flex: 1,
        minWidth: 0,
        fontSize: 16,
        fontWeight: '800',
    },
    sectionManagerCloseButton: {
        width: 34,
        height: 34,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sectionManagerAddButton: {
        minHeight: 42,
        borderRadius: 10,
        borderWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingHorizontal: 12,
        paddingVertical: 9,
    },
    sectionManagerAddButtonText: {
        flexShrink: 1,
        fontSize: 14,
        fontWeight: '800',
    },
    sectionEditor: {
        borderRadius: 10,
        borderWidth: 1,
        gap: 8,
        padding: 10,
    },
    sectionEditorLabel: {
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    sectionEditorInput: {
        borderWidth: 1,
        borderRadius: 8,
        fontSize: 16,
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    sectionEditorActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 8,
    },
    sectionManagerEmpty: {
        borderRadius: 10,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    sectionManagerList: {
        maxHeight: 280,
        borderRadius: 10,
        borderWidth: 1,
    },
    sectionManagerListContent: {
        paddingVertical: 2,
    },
    sectionManagerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
        paddingHorizontal: 10,
        paddingVertical: 9,
        borderBottomWidth: 1,
    },
    sectionManagerRowTitleWrap: {
        flex: 1,
        minWidth: 0,
    },
    sectionManagerRowTitle: {
        fontSize: 14,
        fontWeight: '700',
    },
    sectionManagerRowActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        flexShrink: 0,
    },
    sectionManagerOrderButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    sectionManagerIconButton: {
        width: 30,
        height: 30,
        borderRadius: 8,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sectionManagerIconButtonDisabled: {
        opacity: 0.4,
    },
    areaManagerList: {
        paddingBottom: 8,
    },
    areaManagerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    areaSortButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    areaSortButton: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        borderWidth: 1,
    },
    areaSortText: {
        fontSize: 12,
        fontWeight: '600',
    },
    areaManagerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 8,
        borderBottomWidth: 1,
    },
    areaManagerItem: {
        flexDirection: 'column',
    },
    areaColorPickerRow: {
        flexDirection: 'row',
        paddingBottom: 8,
        paddingLeft: 28,
        gap: 10,
        flexWrap: 'wrap',
    },
    areaManagerInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    areaManagerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    areaManagerText: {
        fontSize: 14,
        fontWeight: '600',
    },
    areaOrderButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginRight: 8,
    },
    colorToggleButton: {
        padding: 6,
        borderRadius: 8,
        borderWidth: 1,
    },
    areaOrderButton: {
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    areaOrderButtonDisabled: {
        opacity: 0.5,
    },
    areaOrderText: {
        fontSize: 12,
        fontWeight: '700',
    },
    areaDeleteButton: {
        paddingHorizontal: 6,
        paddingVertical: 4,
    },
    areaDeleteButtonDisabled: {
        opacity: 0.6,
    },
    areaDeleteText: {
        fontSize: 12,
        fontWeight: '700',
    },
    pickerCard: {
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        minWidth: 280,
        maxWidth: 360,
    },
    pickerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 10,
        borderBottomWidth: 1,
    },
    pickerRowText: {
        fontSize: 14,
        fontWeight: '600',
    },
    areaDot: {
        width: 10,
        height: 10,
        borderRadius: 999,
    },
    tagInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 8,
        marginTop: 10,
    },
    tagInput: {
        flex: 1,
        paddingVertical: 8,
        fontSize: 14,
    },
    tagAddButton: {
        borderLeftWidth: 1,
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    tagAddButtonText: {
        fontSize: 16,
        fontWeight: '700',
    },
    tagOptions: {
        marginTop: 12,
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    tagOption: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: 1,
    },
    tagOptionText: {
        fontSize: 12,
        fontWeight: '600',
    },
    linkModalButton: {
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 10,
    },
    linkModalButtonText: {
        fontSize: 14,
        fontWeight: '700',
    },
    linkModalButtonDisabled: {
        opacity: 0.5,
    },
    reviewContainer: {
        borderBottomWidth: 1,
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    projectSettingsRowSpacing: {
        marginTop: 12,
    },
    projectManageActions: {
        flexDirection: 'row',
        gap: 8,
        marginTop: 12,
    },
    projectManageButton: {
        flex: 1,
        minHeight: 38,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        borderWidth: 1,
        paddingHorizontal: 10,
    },
    reviewLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        marginBottom: 6,
    },
    reviewLabel: {
        fontSize: 14,
        fontWeight: '600',
    },
    reviewButton: {
        padding: 10,
        borderRadius: 8,
        borderWidth: 1,
    },
    clearReviewBtn: {
        marginTop: 6,
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        backgroundColor: '#e5e5e5',
    },
    clearReviewText: {
        fontSize: 12,
        fontWeight: '600',
    },
    focusButton: {
        padding: 8,
    },
});
